easylistpolish/easylistpolish

easylistpolish/easylistpolish_adservers.txt

https://github.com/easylist/easylist/pull/3777

A: https://www.ngo.pl/

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

Remove obsolete hide filters for sites B-K

---

easylistpolish/easylistpolish_specific_block.txt

ebelchatow.pl

---

easylistpolish/easylistpolish_whitelist.txt

[adw.org.pl](http://adw.org.pl)
**false positive**

Issue Reporter - adw.org.pl

---

easylistpolish/easylistpolish_whitelist.txt

[selgros24.pl](https://selgros24.pl)
**autopromocja**
___________

Issue Reporter - selgros24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[goral.info.pl](https://goral.info.pl/kontrola-sanitarna-na-granicy-polsko-slowackiej-w-malopolsce/)

goral.info.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[wysokomazowiecki24.pl](https://wysokomazowiecki24.pl/news/podlaskie/10754.html)

wysokomazowiecki24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[naszwodzislaw.com](https://www.naszwodzislaw.com/site/index)-[naszrybnik.com](https://www.naszrybnik.com/site/index)

naszwodzislaw.com

---

easylistpolish/easylistpolish_specific_block.txt

-[naszrybnik.com](https://www.naszrybnik.com/site/index)-[naszwodzislaw.com](https://www.naszwodzislaw.com/site/index)

naszrybnik.com

---

easylistpolish/easylistpolish_specific_hide.txt

-[trzemeszno24.info](http://trzemeszno24.info/maseczki-trafia-do-mieszkancow-i-sluzb/)

trzemeszno24.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[24starogard.pl](http://www.24starogard.pl)

24starogard.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[androidpolska.pl](https://androidpolska.pl)

androidpolska.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[magazynfakty.pl](https://magazynfakty.pl/gigantyczne-pensje-dyrektorow-politykow/)

magazynfakty.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[ambassador24.pl](http://ambassador24.pl/jakie-sa-roznice-miedzy-rrso-a-rso/)

ambassador24.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[rynekinwestycji.pl](https://rynekinwestycji.pl)

rynekinwestycji.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[beskidlive.pl](https://beskidlive.pl)

beskidlive.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[biznestuba.pl](https://biznestuba.pl)

biznestuba.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[businessjournal.pl](https://businessjournal.pl)

businessjournal.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[bezdroza.pl](https://bezdroza.pl)

bezdroza.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[lexus-forum.pl](http://lexus-forum.pl)

lexus-forum.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

ostrodanews.pl

---

easylistpolish/easylistpolish_specific_hide.txt

ostrodaflesz.pl SH

---

easylistpolish/easylistpolish_specific_block.txt

tvbraniewo24.pl SB

---

easylistpolish/easylistpolish_specific_hide.txt
easylistpolish/easylistpolish_whitelist_popup.txt

-[animezone.pl](https://www.animezone.pl/anime/hack-g-u-returner)

animezone.pl

---

easylistpolish/easylistpolish_specific_hide.txt

elektroda.pl - reklama i sponsorowane #673

elektroda fix issue

---

easylistpolish/easylistpolish_whitelist.txt

-[reklama.prokopienko.pl](http://reklama.prokopienko.pl/)

reklama.prokopienko.pl

---

easylistpolish/easylistpolish_whitelist.txt

-[reklama.zsmeie.torun.pl](https://reklama.zsmeie.torun.pl/)

reklama.zsmeie.torun.pl

---

easylistpolish/easylistpolish_specific_hide.txt

naszglospoznanski.pl

---

easylistpolish/easylistpolish_specific_block.txt

lubliniec.info

---

easylistpolish/easylistpolish_specific_hide.txt

kocham.wielun.pl

---

easylistpolish/easylistpolish_specific_hide.txt

siedlcesiedzieje.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

wirtualnygarwolin.pl

---

easylistpolish/easylistpolish_specific_block.txt

tvostrow.pl

---

easylistpolish/easylistpolish_specific_hide.txt

legio24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

palukitv.pl

---

easylistpolish/easylistpolish_specific_block.txt

expresskaszubski.pl

---

easylistpolish/easylistpolish_specific_block.txt

zkaszub.info

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.tomaszowiak.net/wiadomosci/25150/Programowanie-nie-tylko-dla-chlopakow-wywiad-z-uczennica-Technikum-New-Technology

tomaszowiak.net

---

easylistpolish/easylistpolish_specific_hide.txt

-[kardiolo.pl-WP](https://www.kardiolo.pl/leki.htm)

kardiolo.pl-WP

---

easylistpolish/easylistpolish_specific_hide.txt

-[open.fm-WP](https://open.fm/)

open.fm-WP

---

easylistpolish/easylistpolish_specific_hide.txt

-[echirurgia.pl-WP](https://www.echirurgia.pl/wyrostek/ostre_zapalenie_wyrostka.htm)

echirurgia.pl-WP

---

easylistpolish/easylistpolish_specific_hide.txt

tygodnik.szczytno.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[nwloclawek.pl](https://nwloclawek.pl)

nwloclawek.pl

---

easylistpolish/easylistpolish_specific_block.txt

fix issue #831

---

easylistpolish/easylistpolish_specific_hide.txt

radiopik.pl

---

easylistpolish/easylistpolish_specific_block.txt

popup
https://dzierzgon-twojemiasto.pl/2020/05/27/od-soboty-czwarty-etap-luzowania-obostrzen-sprawdz-co-sie-zmieni/

dzierzgon-twojemiasto.pl

---

easylistpolish/easylistpolish_specific_block.txt

emysliborz.pl

---

easylistpolish/easylistpolish_whitelist.txt

fix csbydgoszcz.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[leki.abczdrowie.pl](https://leki.abczdrowie.pl/p/prostogal-1000-spec-przed-rol-prod-gal-l-p-m-l-s-j)

leki.abczdrowie.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[wirtualnemedia.pl](https://www.wirtualnemedia.pl)

wirtualnemedia.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[ppw.fishing](http://ppw.fishing/content.php)

ppw.fishing

---

easylistpolish/easylistpolish_specific_hide.txt

-[futbolnews.pl](https://futbolnews.pl)

futbolnews.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[mojewronki.pl](http://mojewronki.pl/2020/06/jedna-osoba-w-szpitalu-po-groznym-wypadku/)

mojewronki.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[legionisci.com](https://legionisci.com/news/81164_Wyniki_legionistow_w_Lotos_Nord_Cup.html)

legionisci.com

---

easylistpolish/easylistpolish_specific_hide.txt

-[stomil.olsztyn.pl](https://stomil.olsztyn.pl)

stomil.olsztyn.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[openlinksys.info](https://openlinksys.info/news.php)

openlinksys.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[pik.kielce.pl](http://pik.kielce.pl/aktualnosci/mwk-powiekszylo-kolekcje.html)

pik.kielce.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[proszkow.eu](https://www.proszkow.eu)

proszkow.eu

---

easylistpolish/easylistpolish_specific_block.txt

-[naszsrem.pl](https://naszsrem.pl)

naszsrem.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[pozytywniej.pl](https://www.pozytywniej.pl)

pozytywniej.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[mojaleczyca.pl](http://mojaleczyca.pl/?pd=aktualnosci)

mojaleczyca.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[cieszyninfo.pl](http://cieszyninfo.pl)

cieszyninfo.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[nowyoutsourcing.pl](https://nowyoutsourcing.pl)

nowyoutsourcing.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[kierowcyhgv.uk](https://kierowcyhgv.uk)

kierowcyhgv.uk

---

easylistpolish/easylistpolish_specific_block.txt

-[olsztyn.com.pl](https://www.olsztyn.com.pl)

olsztyn.com.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[naszagazeta.info](https://naszagazeta.info/)

naszagazeta.info

---

easylistpolish/easylistpolish_specific_block.txt

-[polskiinternet.com](http://www.polskiinternet.com/index.shtml)

polskiinternet.com

---

easylistpolish/easylistpolish_specific_block.txt

-[naszciechanow.pl](https://naszciechanow.pl)

naszciechanow.pl

---

easylistpolish/easylistpolish_specific_hide.txt

opowiecie.info

---

easylistpolish/easylistpolish_specific_hide.txt

starachowicka.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

pojezierze24.pl

---

easylistpolish/easylistpolish_specific_block.txt

moszczenica.info

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

lwowecki.info

---

easylistpolish/easylistpolish_specific_hide.txt

ksiazenice.info

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[radiopiekary.pl](https://www.radiopiekary.pl)

radiopiekary.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[radiofon.fm](http://radiofon.fm)

radiofon.fm

---

easylistpolish/easylistpolish_specific_block.txt

-[wroclife.pl](https://wroclife.pl/nasze-miasto/kariera-biznes/wspierajac-przedsiebiorcow-wspieramy-dolny-slask/)

wroclife.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[mojlask.pl](http://www.mojlask.pl/)

mojlask.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[mecze24.pl](https://www.mecze24.pl/typy-bukmacherskie/rb-lipsk-atletico-madryt/3189811)

mecze24.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[konstancin.com](http://www.konstancin.com/)

konstancin.com

---

easylistpolish/easylistpolish_specific_hide.txt

-[futbolwtv.pl](https://futbolwtv.pl)

futbolwtv.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[miejscawewroclawiu.pl](https://miejscawewroclawiu.pl)

miejscawewroclawiu.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[miasto-gazeta.pl](http://miasto-gazeta.pl/radnego-piotra-karpienie-nalezy-docenic-mimo-wszystko/)

miasto-gazeta.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[radiofest.pl](https://radiofest.pl/)

radiofest.pl

---

easylistpolish/easylistpolish_specific_hide.txt

magazyngitarzysta.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

klimatyzacja.biz

---

easylistpolish/easylistpolish_specific_block.txt

infokonin.pl

---

easylistpolish/easylistpolish_specific_block.txt

wirlandii.pl

---

easylistpolish/easylistpolish_specific_hide.txt

sportowememy.pl

---

easylistpolish/easylistpolish_specific_hide.txt

kujawy.info

---

easylistpolish/easylistpolish_specific_hide.txt

infoplocktv.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.bielsko.tv/24462-wjazd-na-szczyt-wywiad-z-wokalistka-aicha-sloniec-bielsko-biala

bielsko.tv

---

easylistpolish/easylistpolish_specific_hide.txt

kurierprzasnyski.pl

---

easylistpolish/easylistpolish_specific_hide.txt

noweinfo.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

alarmy.org

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

budownictwo.org

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

jedzenie.info.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

ksiegowosc.org

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

opakowania.biz

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

stolarstwo.org

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

wentylacja.biz

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

blacha.biz

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

chlodnictwo.biz

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

metale.org

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

odpylanie.info

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

styropian.biz

---

easylistpolish/easylistpolish_specific_block.txt

-[egorzow.pl](https://egorzow.pl)

egorzow.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[budujesz.info](https://budujesz.info)

budujesz.info

---

easylistpolish/easylistpolish_specific_block.txt

-[zarobmy.se](https://zarobmy.se)

zarobmy.se

---

easylistpolish/easylistpolish_specific_block.txt

-[jpktraders.pl](http://jpktraders.pl/analizy.html#!/posts/Bitcoin---kana-wzrostowy/309)

jpktraders.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[zycie.pila.pl](https://zycie.pila.pl)

zycie.pila.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[43bis.media.pl](http://www.43bis.media.pl/wiadomosci.html)

43bis.media.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[gpcodziennie.pl](https://gpcodziennie.pl)

gpcodziennie.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[wspolnota.org.pl](https://wspolnota.org.pl)

wspolnota.org.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[megatiming.pl](http://megatiming.pl/news/all/1)

megatiming.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[baltic.info.pl](https://baltic.info.pl)

baltic.info.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[dorzeczy.pl](https://dorzeczy.pl/)

dorzeczy.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[sarp.org.pl](http://www.sarp.org.pl)

sarp.org.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[wygasle.net](http://wygasle.net/index.html)

wygasle.net

---

easylistpolish/easylistpolish_specific_hide.txt

-[skawinska.pl](https://skawinska.pl)

skawinska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[skijumping.pl](https://www.skijumping.pl)

skijumping.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[winterszus.pl](https://winterszus.pl)

winterszus.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[skokipolska.pl](https://www.skokipolska.pl)

skokipolska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[f1.dziel-pasje.pl](https://f1.dziel-pasje.pl/F1_news-31280-Stella_Sainz_i_Norris_maja_pewne_cechy_wspolne_z_Schumacherem_czy_Alonso.html)

f1.dziel-pasje.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[biegowki.pl](http://biegowki.pl/forum/index.php)

biegowki.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[smart-test.pl](http://smart-test.pl)

smart-test.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[skawina.eu](https://skawina.eu)

skawina.eu

---

easylistpolish/easylistpolish_specific_block.txt

-[slonskyradio.eu](https://slonskyradio.eu)

slonskyradio.eu

---

easylistpolish/easylistpolish_specific_block.txt

-[speedtest.pl](https://www.speedtest.pl)

speedtest.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[katowice.spiz.pl](http://katowice.spiz.pl/index.html)

katowice.spiz.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[spidersweb.pl](https://www.spidersweb.pl/rozrywka/)

spidersweb.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[procesor.pl](https://procesor.pl)

procesor.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[softonet.pl](https://softonet.pl/publikacje/poradniki/Pizza.Hut.z.opcja.zamawiania.jedzenia.przez.Messengera,1992)

softonet.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[sadownictwo.com.pl](https://www.sadownictwo.com.pl)

sadownictwo.com.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[sportrelacje.pl](https://www.sportrelacje.pl/na-zywo/83ed0bd8fe491/lincoln-liverpool)

sportrelacje.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[pieniny24.pl](https://pieniny24.pl)

pieniny24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[stacja-tluszcz.pl](http://stacja-tluszcz.pl)

stacja-tluszcz.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[stalenierdzewne.pl](http://stalenierdzewne.pl)

stalenierdzewne.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[spottedskarzysko.pl](spottedskarzysko.pl)

spottedskarzysko.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[spotradomsko.pl](spotradomsko.pl)

spotradomsko.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

iloveslubice.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[sulecin24.pl](https://sulecin24.pl/)

sulecin24.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[super-warez.eu](http://super-warez.eu/)

super-warez.eu

---

easylistpolish/easylistpolish_specific_hide.txt

-[swiatdronow.pl](http://www.swiatdronow.pl/)

swiatdronow.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[swiatmotocykli.pl](https://swiatmotocykli.pl/)

swiatmotocykli.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[systemyplatnosci.com](https://systemyplatnosci.com/)

systemyplatnosci.com

---

easylistpolish/easylistpolish_specific_block.txt

https://polski-tenis.pl/kolonia-1-atp-hurkacz-i-kubot-na-starcie/

polski-tenis.pl

---

easylistpolish/easylistpolish_specific_hide.txt

news-sport.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://golfnews.pl/sobota-1500-finalowy-mecz-igi-swiatek-w-roland-garros-w-eurosport-i-tvn-player/

golfnews.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://love4tennis.pl/gra-miedzy-punktami-przygotowanie-do-nastepnej-pilki/

love4tennis.pl

---

easylistpolish/easylistpolish_specific_block.txt

e-pingpong.pl

---

easylistpolish/easylistpolish_specific_hide.txt

teksty.org

---

easylistpolish/easylistpolish_specific_hide.txt

http://ekoexpo.pl/pl/pokarmy_pij

ekoexpo.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.gdziepolek.pl/artykuly/kto-wchodzi-bez-kolejki-do-lekarza-i-apteki

gdziepolek.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[radiogol.pl](http://radiogol.pl)

radiogol.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[szukam-ksiazki.pl](http://szukam-ksiazki.pl)

szukam-ksiazki.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[szydlowiecki.eu](https://szydlowiecki.eu/)

szydlowiecki.eu

---

easylistpolish/easylistpolish_specific_hide.txt

-[techmaniachd.pl](http://www.techmaniachd.pl)

techmaniachd.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[telewizor.eu](http://telewizor.eu)

telewizor.eu

---

easylistpolish/easylistpolish_specific_block.txt

-[telchina.pl](https://telchina.pl/microwear-h8-niezbedne-urzadzenie-na-plenerowy-t38996.html)

telchina.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[techpolska.pl](https://techpolska.pl/recenzja-zestawu-x8100-i-myszy-gamingowej-v240-od-rapoo/)

techpolska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[telewizjaleszno.pl](http://telewizjaleszno.pl)

telewizjaleszno.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[elektroda.pl](https://www.elektroda.pl)
#1176

elektroda.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[terazgabin.pl](https://terazgabin.pl/pl/)

terazgabin.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[terazgostynin.pl](https://terazgostynin.pl/pl/)

terazgostynin.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[terazlipno.pl](https://terazlipno.pl/pl/)

terazlipno.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[antyauto.pl](https://antyauto.pl)

antyauto.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[infomare.pl](https://www.infomare.pl)

infomare.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[transinfo.pl](http://transinfo.pl)

transinfo.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[treningbiegacza.pl](https://treningbiegacza.pl)

treningbiegacza.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[ekstraklasatrolls.pl](https://ekstraklasatrolls.pl/fatalne-zachowanie-kepy-co-on-zrobil-wideo/?fbclid=IwAR0p0udqVHKductFXXGV_eE6CRO0qx52e6ikJ5Miud6K0GE6NNUgxgNTAug)

ekstraklasatrolls.pl

---

easylistpolish/easylistpolish_specific_hide.txt

meczyki.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[tsl-biznes.pl](https://www.tsl-biznes.pl)

tsl-biznes.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[trybawaryjny.pl](https://trybawaryjny.pl)

trybawaryjny.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[tvklodzka.pl](http://www.tvklodzka.pl)

tvklodzka.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[twojatv.info](http://twojatv.info)

twojatv.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[twojskaryszew.pl](https://www.twojskaryszew.pl/kancelaria-adwokacka-lodz/)

twojskaryszew.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[uniejow.net.pl](https://uniejow.net.pl/pl/)

uniejow.net.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[uploaduj.com](https://uploaduj.com)

uploaduj.com

---

easylistpolish/easylistpolish_specific_hide.txt

-[ustrzyki24.pl](http://ustrzyki24.pl)

ustrzyki24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[vampirediaries.pl](http://vampirediaries.pl)

vampirediaries.pl

---

easylistpolish/easylistpolish_specific_hide.txt

jablonka.info

---

easylistpolish/easylistpolish_specific_block.txt

tudeblin.pl

---

easylistpolish/easylistpolish_specific_block.txt

tuwodzislaw.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[walbrzyszek.com](https://www.walbrzyszek.com)

walbrzyszek.com

---

easylistpolish/easylistpolish_specific_hide.txt

-[waszdzienpodniu.pl](http://waszdzienpodniu.pl)

waszdzienpodniu.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[webhostingtalk.pl](https://www.webhostingtalk.pl)

webhostingtalk.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://gazeta.myslenice.pl/bracia-ktorzy-pisali-historie-polskiej-pilki

gazeta.myslenice.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.whitemad.pl/marka-elementy-swietuje-5-urodziny-z-tej-okazji-powstal-wyjatkowy-projekt-relove/

whitemad.pl

---

easylistpolish/easylistpolish_specific_hide.txt

gorlice24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.krynica-zdroj.net/krynica-zdroj-pozar-budynku-w-trakcie-budowy/

krynica-zdroj.net

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.nowy-sacz.info/nowy-sacz-prezydent-dementuje-falszywe-informacje-na-temat-likwidacji-malej-galerii/

nowy-sacz.info

---

easylistpolish/easylistpolish_specific_block.txt

miastons.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.filmweb.pl/serial/Dr+House-2004-130177

filmweb.pl

---

easylistpolish/easylistpolish_specific_hide.txt

interia.pl issue#1323

---

easylistpolish/easylistpolish_specific_block.txt

https://www.anonse-krosno.pl/ogloszenia/uslugi-firmy/ad/budowa-i-remont-1103/kompleksowe-us%C5%82ugi-brukarskie-oraz-prace-ziemne-4066

anonse-krosno.pl

---

easylistpolish/easylistpolish_specific_hide.txt

jasionka24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

cenyrolnicze.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

https://goldap.org.pl/2020/11/pasowanie-na-czytelnika-mala-ksiazka-wielki-czlowiek/

goldap.org.pl

---

easylistpolish/easylistpolish_specific_hide.txt

http://info-ketrzyn24.pl/category/wiadomosci/

info-ketrzyn24.pl

---

easylistpolish/easylistpolish_specific_block.txt

mazury.info.pl

---

easylistpolish/easylistpolish_specific_block.txt

mazury24.eu

---

easylistpolish/easylistpolish_specific_hide.txt

-[wiadomoscikosmetyczne.pl](https://www.wiadomoscikosmetyczne.pl/#)

wiadomoscikosmetyczne.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[wieliczkacity.pl](http://www.wieliczkacity.pl)

wieliczkacity.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[wiesci.com.pl](https://wiesci.com.pl)

wiesci.com.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[wiesci.info.pl](https://wiesci.info.pl)

wiesci.info.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://krosno112.pl/aktualnosci/wypadki-kolizje/item/9542-kierujaca-stracila-panowanie-nad-bmw-wjechala-w-audi.html

krosno112.pl

---

easylistpolish/easylistpolish_specific_block.txt

https://socialpress.pl/2020/11/wewnetrzna-ankieta-facebooka-pokazuje-jaki-wplyw-ma-serwis-na-spoleczenstwo

socialpress.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

gostynin.info

---

easylistpolish/easylistpolish_thirdparty.txt

https://mamajakty.pl/szkola-rodzenia-dlaczego-jest-tak-wazna/

mamajakty.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

https://www.tv-pelplin.pl/index.php

tv-pelplin.pl

---

easylistpolish/easylistpolish_specific_block.txt

otososnowiec.pl

---

easylistpolish/easylistpolish_specific_hide.txt

tarnogorski.info

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.lokalnyreporter.pl/

lokalnyreporter.pl

---

easylistpolish/easylistpolish_specific_hide.txt

infozlocieniec.pl

---

easylistpolish/easylistpolish_specific_hide.txt

swidnica24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

naszstrzegom.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://tvwalbrzych.pl/?p=3734

tvwalbrzych.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.24gliwice.pl/wiadomosci/

24gliwice.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://wiadomosciwalbrzyskie.pl/na-nich-zawsze-mozna-liczyc-foto/

wiadomosciwalbrzyskie.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://dzierzgon.info.pl/sukces-na-festiwalu-w-gdyni-oraz-warsztaty-w-bagarcie-i-bruku-zagladamy-do-dok/

dzierzgon.info.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[lokalnatelewizja.pl](https://www.lokalnatelewizja.pl)

lokalnatelewizja.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[lowking.pl](https://www.lowking.pl/stawialbym-na-niego-nawet-w-walce-z-jonesem-rosyjska-legenda-z-wielkim-uznaniem-o-blachowiczu/)

lowking.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[planowaniewesela.pl](http://www.planowaniewesela.pl)

planowaniewesela.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[avokado.blogi.pl](https://avokado.blogi.pl)

avokado.blogi.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[linkologia.pl](https://linkologia.pl)

linkologia.pl

---

easylistpolish/easylistpolish_specific_block.txt

http://www.zywiecsupernowa.pl/

zywiecsupernowa.pl

---

easylistpolish/easylistpolish_specific_hide.txt

http://wdrawskupomorskim.pl/
http://wdrawskupomorskim.pl/poligon-drawski-odnaleziono-i-zniszczono-116-szt-przedmiotow-niebezpiecznych,a4401

wdrawskupomorskim.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

https://kanonierzy.com/news/martinez-triumfuje-nad-bylym-zespolem-arsenal-0-3-aston-villa/50687/

kanonierzy.com

---

easylistpolish/easylistpolish_specific_hide.txt

https://sieradz.com.pl/wiadomosci/

sieradz.com.pl

---

easylistpolish/easylistpolish_specific_hide.txt

http://naszaokolica24.pl/wiadomosci.html

naszaokolica24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

infoprzasnysz.com

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

https://dziennikmazowiecki.pl/

dziennikmazowiecki.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

https://panoramakutna.pl/category/polityka/

panoramakutna.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[zmianysolarne.pl](http://zmianysolarne.pl/wiadomosc/mozliwy-wzrost-aktywnosci-slonecznej-pojawiaja-sie-nowe-aktywne-regiony)

zmianysolarne.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[innemedium.pl](https://innemedium.pl/wiadomosc/czy-titanic-mogl-zatonac-z-powodu-zorzy-polarnej)

innemedium.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[jejportal.pl](https://jejportal.pl/wiadomosc/co-jesc-sniadanie-aby-nie-przytyc)

jejportal.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[tylkoastronomia.pl](https://tylkoastronomia.pl/wiadomosc/sensacja-astronomiczna-odkryto-nieznane-dotychczas-obiekty-w-ukladzie-slonecznym)

tylkoastronomia.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[zmianynaziemi.pl](https://zmianynaziemi.pl)

zmianynaziemi.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[tylkoprzyroda.pl](http://tylkoprzyroda.pl/wiadomosc/potomstwo-zmodyfikowanych-genetycznie-gasienic-ulegnie-samozniszczeniu)

tylkoprzyroda.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[superdania.pl](https://superdania.pl/wiadomosc/gotowy-zestaw-sushi-alternatywny-fastfood)

superdania.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[zloty-pociag.com](http://www.zloty-pociag.com)

zloty-pociag.com

---

easylistpolish/easylistpolish_specific_hide.txt

droneclub.pl

---

easylistpolish/easylistpolish_specific_hide.txt

trzcianka.info

---

easylistpolish/easylistpolish_specific_hide.txt

https://podlaskie.tv/ciezki-sprzet-w-rzecze-tak-urzednicy-niszcza-narew/

podlaskie.tv

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

https://www.slowopodlasia.pl/wiadomosci/11575,losice-nowy-komendant

slowopodlasia.pl

---

easylistpolish/easylistpolish_specific_block.txt

podlasie24.pl

---

easylistpolish/easylistpolish_specific_block.txt

http://www.katalogprzedsiebiorstw.pl/black-on-white-creative-agency.html

katalogprzedsiebiorstw.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

http://nieruchomosci-komercyjne.info/darmowe/index.php?m=advert&s=show&aid=22787#starttxt

nieruchomosci-komercyjne.info

---

easylistpolish/easylistpolish_specific_hide.txt

http://www.ogloszenia-nieruchomosci.info/agencje/index.php?m=advert&s=show&aid=2577211

ogloszenia-nieruchomosci.info

---

easylistpolish/easylistpolish_specific_hide.txt

http://nieruchomosci-bez-posrednikow.com.pl/index.php?m=advert&s=show&aid=22762&sd=&sort=#starttxt

nieruchomosci-bez-posrednikow.com.pl

---

easylistpolish/easylistpolish_specific_hide.txt

http://www.firmy-uslugi24.pl/index.php?m=card&s=show&aid=4993&sd=&sort=

firmy-uslugi24.pl

---

easylistpolish/easylistpolish_specific_block.txt

goleniowska.com

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

portalpomorza.pl

---

easylistpolish/easylistpolish_specific_block.txt

https://przemyslkosmetyczny.pl/

przemyslkosmetyczny.pl

---

easylistpolish/easylistpolish_specific_block.txt

https://www.rynekpapierniczy.pl/

rynekpapierniczy.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.controllingirachunkowosc.pl/

controllingirachunkowosc.pl

---

easylistpolish/easylistpolish_specific_hide.txt

e-commerce-24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.finanseicontrolling.pl/

finanseicontrolling.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.magazyn-produkcja.pl/

magazyn-produkcja.pl

---

.gitattributes

Merge conflict resolving

---

easylistpolish/easylistpolish_specific_hide.txt

kociewiak.pl popup

---

easylistpolish/easylistpolish_specific_hide.txt

-[salebiznesowe.pl](https://www.salebiznesowe.pl)

salebiznesowe.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[linia.com.pl](https://linia.com.pl)

linia.com.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[biznes-hotel.pl](https://www.biznes-hotel.pl)

biznes-hotel.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[gotujmy.pl](https://gotujmy.pl/kategoria-promowana-grudzien,konkursy-konkurs,197.html)

gotujmy.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[itbiznes.pl](https://itbiznes.pl/poradnik/migracja-do-chmury/)

itbiznes.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[radioccm.pl](https://radioccm.pl)

radioccm.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[urzadzamy.pl](https://www.urzadzamy.pl/porady/dekoracje-do-domu/zimowe-przybranie-domu-dobre-pomysly-inspirujace-zdjecia-aa-dess-LymY-Vweh.html)

urzadzamy.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[prestizowydom.pl](http://www.prestizowydom.pl/kolekcja-enigma-nowy-wymiar-designu)

prestizowydom.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[rekomendowanefirmy.pl](http://www.rekomendowanefirmy.pl)

rekomendowanefirmy.pl

---

easylistpolish/easylistpolish_specific_block.txt

https://www.materialybudowlane.info.pl/pl/

materialybudowlane.info.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.oswiecimonline.pl/

oswiecimonline.pl

---

easylistpolish/easylistpolish_specific_hide.txt

tczewska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[dailyweb.pl](https://dailyweb.pl)

dailyweb.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[swiatoze.pl](https://swiatoze.pl/zelazko-solarne-innowacyjny-projekt-hinduskiej-uczennicy/)

swiatoze.pl

---

easylistpolish/easylistpolish_general_hide.txt

Line 25 contains duplicated filter with another one from EasyList. FILTER: ###extraAdsBlock

[redundant] ###extraAdsBlock

---

easylistpolish/easylistpolish_specific_hide.txt

trawka.org, rte24.eu, rmi24.eu, make-cash.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[jozefow-news.pl](http://jozefow-news.pl)

jozefow-news.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[make-cash.pl](https://make-cash.pl)

make-cash.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[trawka.org](https://trawka.org)

trawka.org

---

easylistpolish/easylistpolish_specific_hide.txt

-[siechnice.com.pl](https://siechnice.com.pl)

siechnice.com.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[strzelec.info](https://www.strzelec.info/wiadomosci/1461,zmarla-mloda-strzelczanka)

strzelec.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[rydzyna24.pl](https://rydzyna24.pl)

rydzyna24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[pilkawregionie.pl](https://pilkawregionie.pl)

pilkawregionie.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[gazetaslezanska.pl](https://gazetaslezanska.pl/wywiad-z-wojciechem-bochnakiem/)

gazetaslezanska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[gazetaregionalna.com](https://gazetaregionalna.com)

gazetaregionalna.com

---

easylistpolish/easylistpolish_specific_hide.txt

-[codziennikmlawski.pl](https://codziennikmlawski.pl)

codziennikmlawski.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[superportal24.pl](https://superportal24.pl)

superportal24.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[krs-online.com.pl](http://www.krs-online.com.pl)

krs-online.com.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[tarnobrzeg.info](https://www.tarnobrzeg.info)

tarnobrzeg.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[lesko.info](https://lesko.info)

lesko.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[kalisz24.info.pl](https://kalisz24.info.pl)

kalisz24.info.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[dzwignice.info](https://dzwignice.info)

dzwignice.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[posbud.com.pl](http://posbud.com.pl/start/)

posbud.com.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[czest.info](http://czest.info)

czest.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[wkielcach.info](https://wkielcach.info)

wkielcach.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[twojaslupca.pl](https://twojaslupca.pl)

twojaslupca.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[maksymalnie.pl](http://maksymalnie.pl)

maksymalnie.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[wkatalog.pl](http://wkatalog.pl)

wkatalog.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[buduj-remontuj-urzadzaj.pl](http://buduj-remontuj-urzadzaj.pl)

buduj-remontuj-urzadzaj.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[miejskieinfo.pl](http://miejskieinfo.pl)

miejskieinfo.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[oto-slub.pl](http://oto-slub.pl)-[moto-oto.pl](http://moto-oto.pl)-[katalog.ospi.pl](http://katalog.ospi.pl)-[lekarze-gabinety.pl](http://lekarze-gabinety.pl)

oto-slub.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[gryfice24.online](https://gryfice24.online)

gryfice24.online

---

easylistpolish/easylistpolish_specific_hide.txt

-[4programmers.net](https://4programmers.net)

4programmers.net

---

easylistpolish/easylistpolish_specific_hide.txt

-[kolbuszowalokalnie.pl](https://kolbuszowalokalnie.pl)

kolbuszowalokalnie.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[stargardzka.pl](https://stargardzka.pl)

stargardzka.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[pod24.info](http://pod24.info)

pod24.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[karnickie.info](http://karnickie.info)

karnickie.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[jakodzyskacpieniadze.pl](https://jakodzyskacpieniadze.pl)

jakodzyskacpieniadze.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[luzna24.pl](http://luzna24.pl)

luzna24.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[izabrze.pl](https://izabrze.pl)

izabrze.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[ogrodinfo.pl](https://www.ogrodinfo.pl/sadownictwo/)

ogrodinfo.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[infogliwice.pl](https://infogliwice.pl)

infogliwice.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[faktura.pl](https://faktura.pl)

faktura.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[iotwock.info](https://iotwock.info)

iotwock.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[konecki24.pl](https://konecki24.pl)

konecki24.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[edzieci.pl](http://edzieci.pl)

edzieci.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[przeglad-ogrodniczy.pl](https://przeglad-ogrodniczy.pl)

przeglad-ogrodniczy.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[fit-online.pl](https://fit-online.pl)

fit-online.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[mleczarnieonline.pl](https://mleczarnieonline.pl)

mleczarnieonline.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[piekarnieonline.pl](https://piekarnieonline.pl)

piekarnieonline.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[namasce.pl](https://namasce.pl)

namasce.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[bialogardzianin.pl](https://bialogardzianin.pl)

bialogardzianin.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[cozadzien.pl](https://www.cozadzien.pl)

cozadzien.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[ibielany.pl](https://ibielany.pl)

ibielany.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://moviesroom.pl/newsy/komiksy/czy-punisher-zostanie-usuniety/

moviesroom.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.urania.edu.pl/wiadomosci/ladownik-marsjanski-insight-bedzie-dzialal-do-2022-roku-polski-kret-jeszcze-sprobuje-sie

urania.edu.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://wolna-polska.pl/wiadomosci/kulisy-smierci-jana-pawla-i-dr-paul-l-williams-2021-01

wolna-polska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

http://nieznanyswiat.pl/nieznany-%C5%9Bwiat/aktualno%C5%9Bci-n%C5%9B/2151-prog_astrol21

nieznanyswiat.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

https://wiecbork112.pl/nietrzezwy-bez-uprawnien-kierowal-samochodem/

wiecbork112.pl

---

easylistpolish/easylistpolish_specific_block.txt

oswiecim112.pl

---

easylistpolish/easylistpolish_specific_block.txt

bielsko.info

---

easylistpolish/easylistpolish_specific_block.txt

https://112malopolska.pl/pozar-mieszkania-w-brzeszczach-strazacy-ewakuowali-mieszkancow/

112malopolska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

http://gniezno112.pl/wjechal-samochodem-wody/

gniezno112.pl

---

easylistpolish/easylistpolish_specific_block.txt

sanok112.pl

---

easylistpolish/easylistpolish_specific_block.txt

112wadowice.pl

---

easylistpolish/easylistpolish_specific_hide.txt

radioandrychow.pl

---

easylistpolish/easylistpolish_specific_block.txt

https://www.infomalopolska.pl/

infomalopolska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

http://www.firmowy.com.pl/start-office,f3706

firmowy.com.pl

---

easylistpolish/easylistpolish_specific_hide.txt

budoskop.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

https://koscian112.pl/2021/01/13/smiertelne-potracenie-na-starej-piatce-sprawca-uciekl/

koscian112.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

zrobotyzowany.pl

---

easylistpolish/easylistpolish_specific_hide.txt

nolesnica.pl

---

easylistpolish/easylistpolish_specific_hide.txt

stockwatch.pl

---

easylistpolish/easylistpolish_specific_hide.txt

polukr.net

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.polakwholandii.nl/

polakwholandii.nl

---

easylistpolish/easylistpolish_specific_hide.txt

magazynit.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

nasygnale.com.pl

---

easylistpolish/easylistpolish_specific_hide.txt

ittechblog.pl

---

easylistpolish/easylistpolish_specific_block.txt

https://www.echotygodnik.info/wiadomosci

echotygodnik.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[tyna.info.pl](https://tyna.info.pl)

tyna.info.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[miejska.info.pl](https://www.miejska.info.pl)-[ktomalek.pl](https://ktomalek.pl/blog/soczewki-kontaktowe-czy-okulary-co-wybrac/w-1767)

miejska.info.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[botland.com.pl](https://botland.com.pl)

botland.com.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[bieganie.pl](https://bieganie.pl)

bieganie.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[poradnikzdrowie.pl](https://www.poradnikzdrowie.pl/diety-i-zywienie/co-jesz/kompot-z-suszu-wlasciwosci-zdrowotne-przepis-na-zdrowy-kompot-wigilijny-aa-DmP3-TNTN-6tHp.html)

poradnikzdrowie.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[komputery-pc.info](https://komputery-pc.info)

komputery-pc.info

---

easylistpolish/easylistpolish_specific_block.txt

-[kurier-kolski.pl](https://kurier-kolski.pl/2021/01/olimpijki-a-sulinskiej-nominowane-do-nagrody-grand-press-dla-ksiazki-reporterskiej-roku-i-w-plebiscycie-na-sportowa-ksiazke-roku-2020/)

kurier-kolski.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[polska-zbrojna.pl](http://polska-zbrojna.pl/#)

polska-zbrojna.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[bochniazbliska.pl](https://bochniazbliska.pl)

bochniazbliska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[appleworld.pl](https://appleworld.pl)

appleworld.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[radioem.pl](https://www.radioem.pl)

radioem.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[automotivesuppliers.pl](https://www.automotivesuppliers.pl/pl/)

automotivesuppliers.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[bosonamacie.pl](https://bosonamacie.pl)

bosonamacie.pl

---

easylistpolish/easylistpolish_specific_hide.txt

http://www.production-manager.pl/

production-manager.pl

---

easylistpolish/easylistpolish_specific_hide.txt

tarnowiak.pl

---

easylistpolish/easylistpolish_specific_hide.txt

gazetakolobrzeska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

http://www.glogow-info.pl/index.php

glogow-info.pl

---

easylistpolish/easylistpolish_specific_block.txt

https://www.portalwolow.pl/farby-ktorych-szukamy/

portalwolow.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

nowagazeta.pl

---

easylistpolish/easylistpolish_specific_hide.txt

tydzien.net.pl

---

easylistpolish/easylistpolish_specific_block.txt

zulawy.com

---

easylistpolish/easylistpolish_specific_hide.txt

itvwisla.tv

---

easylistpolish/easylistpolish_specific_hide.txt

https://4miasta.pl/stalowa-wola/strajk-kobiet-w-stalowej-woli-buntu-ciag-dalszy/

4miasta.pl

---

easylistpolish/easylistpolish_specific_hide.txt

https://www.tvswietokrzyska.pl/

tvswietokrzyska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

gazeta-mlawska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

wawernews.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[otomoto.pl](https://www.otomoto.pl)

otomoto.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[mazopolska.pl](https://mazopolska.pl)

mazopolska.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[bogatyregion.pl](https://bogatyregion.pl)

bogatyregion.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[miastokobiet.pl](https://www.miastokobiet.pl)

miastokobiet.pl

---

easylistpolish/easylistpolish_specific_block.txt

-[rowery.org](https://rowery.org)

rowery.org

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[wirtualnyregion.pl](https://wirtualnyregion.pl)

wirtualnyregion.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[e-playonline.com](https://e-playonline.com/)

e-playonline.com

---

easylistpolish/easylistpolish_specific_block.txt

-[retailnet.pl](https://retailnet.pl)

retailnet.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[magazynt3.pl](https://magazynt3.pl)

magazynt3.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[gazetasenior.pl](https://www.gazetasenior.pl)

gazetasenior.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[mojanorwegia.pl](https://www.mojanorwegia.pl)

mojanorwegia.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[anywhere.pl](https://www.anywhere.pl)

anywhere.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

-[bolec.info](https://www.bolec.info/index.php)

bolec.info

---

easylistpolish/easylistpolish_specific_block.txt

-[lokalna.info](http://lokalna.info)

lokalna.info

---

easylistpolish/easylistpolish_specific_hide.txt

-[naszestrony.info.pl](https://naszestrony.info.pl)

naszestrony.info.pl

---

easylistpolish/easylistpolish_specific_hide.txt

-[zlubaczowa.pl](https://zlubaczowa.pl)

zlubaczowa.pl

---

easylistpolish/easylistpolish_specific_hide.txt

http://www.dziennikteatralny.pl/index

dziennikteatralny.pl

---

easylistpolish/easylistpolish_specific_block.txt
easylistpolish/easylistpolish_specific_hide.txt

http://www.budownictwo.co/zima-bez-niespodzianek-co-zrobic-zeby-brama-dzialala-bez-zarzutu/

budownictwo.co
