easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
=> rynek-rolny.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
=> dwakwadranse.pl

easylistpolish/easylistpolish_specific_block.txt
https://napoli24h.pl/news.php?readmore=5244
=> napoli24h.pl

easylistpolish/easylistpolish_specific_block.txt
https://www.malagacf.pl/2021/02/pierwsza-szostka-prawie-z-kompletem-zwyciestw-co-wiemy-po-22-kolejce-la-liga/
=> malagacf.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.widzewtomy.net/pierwszy-tysiac-karnetow-znalazl-swoich-nabywcow/
=> widzewtomy.net

easylistpolish/easylistpolish_specific_hide.txt
http://www.stylkibica.net/mecz-fazy-pucharowej-ligi-mistrzow-w-warszawie/
=> stylkibica.net

easylistpolish/easylistpolish_specific_hide.txt
http://terazpasy.pl/Pilka-nozna/konferencje_prasowe/Konferencja-prasowa-przed-meczem-Pogon-Szczecin-Cracovia
=> terazpasy.pl

easylistpolish/easylistpolish_specific_hide.txt
http://motorlublin.com/2021/01/03/zolto-bialo-niebieska-gwiazdka-2/
=> motorlublin.com

easylistpolish/easylistpolish_specific_hide.txt
https://www.spottedalert.pl/kraj/policja-prawie-120-naruszen-zakazow-lub-nakazow-wydanych-na-mocy-ustawy-antyprzemocowej/
=> spottedalert.pl

easylistpolish/easylistpolish_specific_block.txt
https://www.plastech.pl/wiadomosci/Jubileusz-w-dobie-pandemii-16227
=> plastech.pl

easylistpolish/easylistpolish_specific_hide.txt
-[naszabramow.pl](https://naszabramow.pl)
=> naszabramow.pl

easylistpolish/easylistpolish_specific_hide.txt
-[ciechanowonline.pl](http://www.ciechanowonline.pl)
=> ciechanowonline.pl

easylistpolish/easylistpolish_specific_hide.txt
-[twojepajeczno.pl](https://twojepajeczno.pl)
=> twojepajeczno.pl

easylistpolish/easylistpolish_specific_block.txt
-[e-lokalne.pl](http://e-lokalne.pl/index2.php?idmodyf=41&tab=lokalneczytanie)
=> e-lokalne.pl

easylistpolish/easylistpolish_specific_hide.txt
-[capuccino.eu](https://capuccino.eu)
=> capuccino.eu

easylistpolish/easylistpolish_specific_hide.txt
-[miechowski.pl](https://www.miechowski.pl)
=> miechowski.pl

easylistpolish/easylistpolish_specific_hide.txt
-[glosrybnika.pl](http://www.glosrybnika.pl)
=> glosrybnika.pl

easylistpolish/easylistpolish_specific_hide.txt
-[glosrzeszowa.pl](http://www.glosrzeszowa.pl)
=> glosrzeszowa.pl

easylistpolish/easylistpolish_specific_hide.txt
-[hodowle.eu](http://www.hodowle.eu)
=> hodowle.eu

easylistpolish/easylistpolish_specific_hide.txt
-[magazynbiomasa.pl](https://magazynbiomasa.pl)
=> magazynbiomasa.pl

easylistpolish/easylistpolish_specific_hide.txt
-[kryptoporadnik.pl](https://www.kryptoporadnik.pl/serwer-dedykowany-kiedy-warto-siegnac-po-to-rozwiazanie/)
=> kryptoporadnik.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[polskatradycja.pl](https://www.polskatradycja.pl/piesni/religijne/zawitaj-krolowo-rozanca-swietego.html)
=> polskatradycja.pl

easylistpolish/easylistpolish_specific_hide.txt
-[polskiemiasta.tv](https://www.polskiemiasta.tv)
=> polskiemiasta.tv

easylistpolish/easylistpolish_specific_hide.txt
-[lubaczow.tv](http://lubaczow.tv/mbp-cieszanow-dziecie-elfow-4/)
=> lubaczow.tv

easylistpolish/easylistpolish_specific_block.txt
-[sportowebeskidy.pl](https://www.sportowebeskidy.pl/iv-liga/wygrana-jest-aspekty-do-poprawy-rowniez)
=> sportowebeskidy.pl

easylistpolish/easylistpolish_specific_hide.txt
-[biznesregion.pl](http://www.biznesregion.pl)
=> biznesregion.pl

easylistpolish/easylistpolish_specific_block.txt
-[trentino.pl](https://www.trentino.pl/trentino/wiosenne-narty-w-trentino-z-cala-rodzina,newsy,7868.html)
=> trentino.pl

easylistpolish/easylistpolish_specific_hide.txt
#1796 
-[nowezyciepabianic.pl](http://www.nowezyciepabianic.pl/wp/)
=> nowezyciepabianic.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[faunaflora.com.pl](http://www.faunaflora.com.pl)
=> faunaflora.com.pl

easylistpolish/easylistpolish_specific_hide.txt
-[staresiolkowice.pl](https://staresiolkowice.pl/stare-siolkowice-co-gdyby/)
=> staresiolkowice.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[wielkopolska.tv](http://wielkopolska.tv)
=> wielkopolska.tv

easylistpolish/easylistpolish_specific_hide.txt
-[gamingsociety.pl](https://gamingsociety.pl)
=> gamingsociety.pl

easylistpolish/easylistpolish_specific_block.txt
-[pionki24.pl](http://pionki24.pl)
=> pionki24.pl

easylistpolish/easylistpolish_specific_hide.txt
-[zwolen24.pl](http://zwolen24.pl)
=> zwolen24.pl

easylistpolish/easylistpolish_specific_hide.txt
-[cztery-lapy.pl](https://cztery-lapy.pl/#)
=> cztery-lapy.pl

easylistpolish/easylistpolish_specific_hide.txt
-[muzyczneradio.pl](https://muzyczneradio.pl)
=> muzyczneradio.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[otouczelnie.pl](https://www.otouczelnie.pl)
=> otouczelnie.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
=> pmi24.info

easylistpolish/easylistpolish_specific_block.txt
https://www.starosadeckie.info/
=> starosadeckie.info

easylistpolish/easylistpolish_specific_hide.txt
https://www.tychy.info/wiadomosci/11202-foto-wideo-wypadek-smiglowca-nie-zyja-pilot-i-biznesmen-k-kania-pszczyna-studzienice
=> tychy.info

easylistpolish/easylistpolish_specific_hide.txt
https://www.koscierzyna24.info/wiadomosci/4721,koscierzyna-specjalna-ankieta-pokaze-czy-oddychamy-czystszym-powietrzem
=> koscierzyna24.info

easylistpolish/easylistpolish_specific_hide.txt
https://www.stefczyk.info/category/gospodarka/
=> stefczyk.info

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
=> pch24.info

easylistpolish/easylistpolish_specific_hide.txt
=> myslenicka24.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
https://www.mojgdow.pl/autobobilklub-galicyjski-podsumowuje-15-edycje-rajdowej-wosp/
=> mojgdow.pl

easylistpolish/easylistpolish_specific_hide.txt
http://mojgdowmagazyn.pl/2020/12/24/wojt-wojas-jest-juz-pelnoletni/
=> mojgdowmagazyn.pl

easylistpolish/easylistpolish_specific_hide.txt
http://polskieligi.net/lukasz-konefal-najblizszy-rok-spedzi-w-wolczance-wolka-pelkinska
=> polskieligi.net

easylistpolish/easylistpolish_specific_hide.txt
-[kurierostrowiecki.pl](https://kurierostrowiecki.pl)
=> kurierostrowiecki.pl

easylistpolish/easylistpolish_specific_hide.txt
-[kurierwilenski.lt](https://kurierwilenski.lt)
=> kurierwilenski.lt

easylistpolish/easylistpolish_specific_block.txt
-[inowroclaw.info.pl](https://inowroclaw.info.pl)
=> inowroclaw.info.pl

easylistpolish/easylistpolish_specific_hide.txt
-[swarzedz24.pl](https://swarzedz24.pl)
=> swarzedz24.pl

easylistpolish/easylistpolish_specific_hide.txt
-[koscianiak.pl](https://koscianiak.pl/nowe-osiedle-w-koscianie-i-problem-z-parkowaniem/)
=> koscianiak.pl

easylistpolish/easylistpolish_specific_hide.txt
-[bobasmiesiaca.pl](https://www.bobasmiesiaca.pl)
=> bobasmiesiaca.pl

easylistpolish/easylistpolish_specific_block.txt
-[archigame.pl](http://archigame.pl)
=> archigame.pl

easylistpolish/easylistpolish_specific_hide.txt
-[grojec24.net](https://www.grojec24.net)
=> grojec24.net

easylistpolish/easylistpolish_specific_hide.txt
-[naszrynek.pl](https://www.naszrynek.pl)
=> naszrynek.pl

easylistpolish/easylistpolish_specific_hide.txt
-[plonskwsieci.pl](https://plonskwsieci.pl/pl/473_na_sygnale/6989_20-letni-plonszczanin-awanturowal-sie-ublizal-kasjerce-byl-opryskliwy-wobec-interweniujacych-policjantow-.html)
=> plonskwsieci.pl

easylistpolish/easylistpolish_specific_hide.txt
-[lebork24.info](http://www.lebork24.info)
=> lebork24.info

easylistpolish/easylistpolish_specific_hide.txt
-[skarzysko24.pl](http://skarzysko24.pl)
=> skarzysko24.pl

easylistpolish/easylistpolish_specific_hide.txt
-[kazanaprawda.pl](zakazanaprawda.pl)
=> kazanaprawda.pl

easylistpolish/easylistpolish_specific_hide.txt
-[centrumxp.pl](https://www.centrumxp.pl/Publikacja/Microsoft-udostepnia-dwa-nowe-narzedzia-eksperymentalne-Edge-DevTools)
=> centrumxp.pl

easylistpolish/easylistpolish_specific_hide.txt
-[oknonet.pl](https://oknonet.pl)
=> oknonet.pl

easylistpolish/easylistpolish_specific_hide.txt
-[planeta.pl](https://www.planeta.pl/Wiadomosci/Swiat/Kolejny-skoczek-chory-na-COVID-19.-Niepokoj-w-polskiej-kadrze-03-03-2021)
=> planeta.pl

easylistpolish/easylistpolish_specific_hide.txt
-[silesia24.pl](https://silesia24.pl)
=> silesia24.pl

easylistpolish/easylistpolish_specific_block.txt
-[zambrow.org](https://zambrow.org)
=> zambrow.org

easylistpolish/easylistpolish_specific_hide.txt
-[magazyn.elubin.pl](http://magazyn.elubin.pl/ofe-do-calkowitej-likwidacji-kazda-decyzja-w-sprawie-zgromadzonych-tam-oszczednosci-bedzie-oznaczac-utrate-czesci-srodkow/)
=> magazyn.elubin.pl

easylistpolish/easylistpolish_specific_hide.txt
-[nowinynyskie.com.pl](https://nowinynyskie.com.pl)
=> nowinynyskie.com.pl

easylistpolish/easylistpolish_specific_block.txt
-[oknonawagrowiec.pl](https://oknonawagrowiec.pl)
=> oknonawagrowiec.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[infobeskidy.eu](http://infobeskidy.eu)
=> infobeskidy.eu

easylistpolish/easylistpolish_specific_hide.txt
-[interia.pl](https://www.interia.pl)
=> interia.pl

easylistpolish/easylistpolish_specific_hide.txt
-[odkrywamyzakryte.com](https://www.odkrywamyzakryte.com)
=> odkrywamyzakryte.com

easylistpolish/easylistpolish_specific_hide.txt
-[ototorun.pl](https://ototorun.pl)
=> ototorun.pl

easylistpolish/easylistpolish_specific_block.txt
-[kontakt-st.pl](http://kontakt-st.pl)
=> kontakt-st.pl

easylistpolish/easylistpolish_specific_block.txt
-[energoelektronika.pl](http://www.energoelektronika.pl/index.jsp)
=> energoelektronika.pl

easylistpolish/easylistpolish_specific_hide.txt
-[itv24.com.pl](http://itv24.com.pl/a,tvwy)
=> itv24.com.pl

easylistpolish/easylistpolish_specific_hide.txt
-[tvopolska.pl](http://tvopolska.pl)
=> tvopolska.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[rolnictwo.com.pl](http://rolnictwo.com.pl)
=> rolnictwo.com.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[trzoda-chlewna.com.pl](https://www.trzoda-chlewna.com.pl/nowa/index.php)
=> trzoda-chlewna.com.pl

easylistpolish/easylistpolish_specific_block.txt
-[darmowetv.pl](https://www.darmowetv.pl/tvn-7)
=> darmowetv.pl

easylistpolish/easylistpolish_specific_hide.txt
-[ceo.com.pl](https://ceo.com.pl)
=> ceo.com.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[lubanski.eu](http://www.lubanski.eu)
=> lubanski.eu

easylistpolish/easylistpolish_specific_block.txt
-[czytelniamedyczna.pl](http://czytelniamedyczna.pl)
=> czytelniamedyczna.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[przekultura.pl](http://przekultura.pl)
=> przekultura.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[przeambitni.pl](https://przeambitni.pl)
=> przeambitni.pl

easylistpolish/easylistpolish_specific_block.txt
-[chelsea24news.pl](https://www.chelsea24news.pl)
=> chelsea24news.pl

easylistpolish/easylistpolish_specific_hide.txt
-[kliknijwzdrowie.pl](https://kliknijwzdrowie.pl)
=> kliknijwzdrowie.pl

easylistpolish/easylistpolish_specific_hide.txt
-[probasket.pl](https://probasket.pl)
=> probasket.pl

easylistpolish/easylistpolish_specific_hide.txt
-[czateria.interia.pl](https://czateria.interia.pl)
=> czateria.interia.pl

easylistpolish/easylistpolish_specific_block.txt
-[ogloszenia.ga](https://ogloszenia.gazeta.ie)
=> ogloszenia.ga

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[rybnik.com.pl](https://www.rybnik.com.pl/index.php/wiadomosci,niezwykle-zdjecia-grzegorza-matli-i-pytania-o-ssaki-naszych-lasow-quiz,wia5-3266-47875.html)
=> rybnik.com.pl

easylistpolish/easylistpolish_specific_block.txt
-[glosmordoru.pl](https://glosmordoru.pl)
=> glosmordoru.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[bielskirynek.pl](https://bielskirynek.pl/pl/)
=> bielskirynek.pl

easylistpolish/easylistpolish_specific_hide.txt
-[bukmacherstwo.info](https://www.bukmacherstwo.info)
=> bukmacherstwo.info

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[bezrzecze24.pl](http://bezrzecze24.pl/news.php)
=> bezrzecze24.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[gumience24.pl](http://gumience24.pl/news.php)
=> gumience24.pl

easylistpolish/easylistpolish_specific_hide.txt
-[glospedagogiczny.pl](https://www.glospedagogiczny.pl)
=> glospedagogiczny.pl

easylistpolish/easylistpolish_specific_block.txt
-[internet-komputery.blogspot.com](http://internet-komputery.blogspot.com)
=> internet-komputery.blogspot.com

easylistpolish/easylistpolish_specific_hide.txt
-[raportkolejowy.pl](https://raportkolejowy.pl)
=> raportkolejowy.pl

easylistpolish/easylistpolish_specific_hide.txt
-[deblinnews.pl](https://deblinnews.pl)
=> deblinnews.pl

easylistpolish/easylistpolish_specific_hide.txt
-[dieroten.pl](https://www.dieroten.pl)
=> dieroten.pl

easylistpolish/easylistpolish_specific_hide.txt
-[samnaprawiam.com](https://samnaprawiam.com)
=> samnaprawiam.com

easylistpolish/easylistpolish_specific_block.txt
-[lubuskie24.pl](https://lubuskie24.pl)
=> lubuskie24.pl

easylistpolish/easylistpolish_specific_hide.txt
-[niebiescy.pl](http://niebiescy.pl)
=> niebiescy.pl

easylistpolish/easylistpolish_adservers.txt
-[druk.info.pl](http://druk.info.pl)
=> druk.info.pl

easylistpolish/easylistpolish_specific_block.txt
-[poligonowewiesci.pl](http://poligonowewiesci.pl)
=> poligonowewiesci.pl

easylistpolish/easylistpolish_specific_block.txt
-[onetexpress.pl](http://onetexpress.pl)
=> onetexpress.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[ecentrum.pl](http://www.ecentrum.pl)
=> ecentrum.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[skawina24.com](https://skawina24.com)
=> skawina24.com

easylistpolish/easylistpolish_specific_hide.txt
-[hij.com.pl](https://hij.com.pl)
=> hij.com.pl

easylistpolish/easylistpolish_specific_hide.txt
-[tonaszregion.pl](https://tonaszregion.pl)
=> tonaszregion.pl

easylistpolish/easylistpolish_specific_hide.txt
-[plonsk24.pl](http://plonsk24.pl)
=> plonsk24.pl

easylistpolish/easylistpolish_specific_hide.txt
-[kodiwpigulce.pl](https://kodiwpigulce.pl)
=> kodiwpigulce.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[gminadobra24.pl](http://gminadobra24.pl/news.php)
=> gminadobra24.pl

easylistpolish/easylistpolish_specific_block.txt
-[lubelszczyzna.info](http://lubelszczyzna.info)
=> lubelszczyzna.info

easylistpolish/easylistpolish_specific_hide.txt
-[emaszyny.pl](http://www.emaszyny.pl)
=> emaszyny.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[instalki.pl](https://www.instalki.pl)
=> instalki.pl

easylistpolish/easylistpolish_specific_block.txt
-[minecraft-list.pl](https://www.minecraft-list.pl/?page=list)
=> minecraft-list.pl

easylistpolish/easylistpolish_specific_hide.txt
-[wiescipolickie.pl](http://wiescipolickie.pl)
=> wiescipolickie.pl

easylistpolish/easylistpolish_specific_block.txt
-[deblin24.eu](http://deblin24.eu)
=> deblin24.eu

easylistpolish/easylistpolish_specific_hide.txt
-[ziemiastrzelecka.strzelce.pl](http://ziemiastrzelecka.strzelce.pl)
=> ziemiastrzelecka.strzelce.pl

easylistpolish/easylistpolish_specific_hide.txt
-[e-chorzow.com](https://www.e-chorzow.com)
=> e-chorzow.com

easylistpolish/easylistpolish_specific_hide.txt
-[tygodnikpiski.pl](http://tygodnikpiski.pl)
=> tygodnikpiski.pl

easylistpolish/easylistpolish_specific_hide.txt
-[nowytygodniklobeski.pl](http://nowytygodniklobeski.pl)
=> nowytygodniklobeski.pl

easylistpolish/easylistpolish_specific_hide.txt
-[dziennikstargardzki.pl](http://www.dziennikstargardzki.pl)
=> dziennikstargardzki.pl

easylistpolish/easylistpolish_specific_hide.txt
-[pojezierze.com.pl](http://pojezierze.com.pl)
=> pojezierze.com.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[przeclaw24.pl](https://przeclaw24.pl)
=> przeclaw24.pl

easylistpolish/easylistpolish_specific_hide.txt
-[genapps.pl](http://genapps.pl)
=> genapps.pl

easylistpolish/easylistpolish_specific_hide.txt
-[historykon.pl](https://historykon.pl)
=> historykon.pl

easylistpolish/easylistpolish_specific_hide.txt
-[powiatpolicki.info](https://powiatpolicki.info)
=> powiatpolicki.info

easylistpolish/easylistpolish_specific_hide.txt
-[chtvl.chrzanow.pl](http://chtvl.chrzanow.pl)
=> chtvl.chrzanow.pl

easylistpolish/easylistpolish_specific_hide.txt
-[pyrzyce.info](http://pyrzyce.info)
=> pyrzyce.info

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[ostrowczanie.info](http://ostrowczanie.info)
=> ostrowczanie.info

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[ogloszenia.tarnobrzeg.info](https://www.ogloszenia.tarnobrzeg.info/6625-lampy-antydepresyjne-klarstein)
=> ogloszenia.tarnobrzeg.info

easylistpolish/easylistpolish_specific_block.txt
-[pogoda.info](https://pogoda.info)
=> pogoda.info

easylistpolish/easylistpolish_specific_hide.txt
-[30minut.pl](https://www.30minut.pl/espresso-z-sandra-ciempa/)
=> 30minut.pl

easylistpolish/easylistpolish_specific_hide.txt
-[kalendarz.pl](https://kalendarz.pl)
=> kalendarz.pl

easylistpolish/easylistpolish_specific_block.txt
-[lubawka.info](http://lubawka.info/gazeta-wroclawska-poinformowala-firma-wolav-wybuduje-w-czarnym-borze-nowy-zaklad-produkcyjny/)
=> lubawka.info

easylistpolish/easylistpolish_specific_block.txt
-[deweloperzy.pl](https://deweloperzy.pl)
=> deweloperzy.pl

easylistpolish/easylistpolish_specific_hide.txt
-[slasknet.com](https://www.slasknet.com)
=> slasknet.com

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[bankier.pl](https://www.bankier.pl)
=> bankier.pl

easylistpolish/easylistpolish_specific_hide.txt
-[android.com.pl](https://android.com.pl)
=> android.com.pl

easylistpolish/easylistpolish_specific_hide.txt
-[stadiony.net](http://stadiony.net)
=> stadiony.net

easylistpolish/easylistpolish_specific_block.txt
-[goniec.com](https://goniec.com/po-godzinach/gadzety/35343-bezprzewodowa-ladowarka-vinyl)
=> goniec.com

easylistpolish/easylistpolish_specific_hide.txt
-[dostawczaki.pl](https://dostawczaki.pl)
=> dostawczaki.pl

easylistpolish/easylistpolish_specific_hide.txt
-[wyspiarzniebieski.pl](http://www.wyspiarzniebieski.pl)
=> wyspiarzniebieski.pl

easylistpolish/easylistpolish_specific_block.txt
-[euslugi.pl](https://euslugi.pl)
=> euslugi.pl

easylistpolish/easylistpolish_specific_hide.txt
-[epainfo.pl](https://epainfo.pl/to-jedyna-taka-pracownia-w-pabianicach-ma-ja-zs-2/)
=> epainfo.pl

easylistpolish/easylistpolish_specific_block.txt
-[crewing.portalmorski.pl](https://crewing.portalmorski.pl)
=> crewing.portalmorski.pl

easylistpolish/easylistpolish_specific_hide.txt
-[swidnik.pl](https://www.swidnik.pl)
=> swidnik.pl

easylistpolish/easylistpolish_specific_block.txt
-[notowania.net](https://notowania.net)
=> notowania.net

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[programtv.info](https://programtv.info)
=> programtv.info

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[mieszkaniec.pl](https://mieszkaniec.pl)
=> mieszkaniec.pl

easylistpolish/easylistpolish_specific_block.txt
-[motocykle125.pl](https://www.motocykle125.pl/ile-motocykli-sprzedali-chinczycy-krotki-przeglad-statystyki/)
=> motocykle125.pl

easylistpolish/easylistpolish_specific_block.txt
-[podrogach.pl](http://podrogach.pl)
=> podrogach.pl

easylistpolish/easylistpolish_specific_hide.txt
-[polskaizbabranzypogrzebowej.pl](http://polskaizbabranzypogrzebowej.pl)
=> polskaizbabranzypogrzebowej.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[polonia-peterborough.uk](https://www.polonia-peterborough.uk)
=> polonia-peterborough.uk

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[kryptowaluty.info.pl](https://kryptowaluty.info.pl)
=> kryptowaluty.info.pl

easylistpolish/easylistpolish_specific_block.txt
-[abc-dachy.pl](http://www.abc-dachy.pl/index.php)
=> abc-dachy.pl

easylistpolish/easylistpolish_specific_hide.txt
-[golfpl.com](https://www.golfpl.com)
=> golfpl.com

easylistpolish/easylistpolish_specific_hide.txt
https://renaultlaguna.pl/forum/gallery/
=> renaultlaguna.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.dziennikwschodni.pl/polityka/starostowie-nie-z-pis-na-drogi-nie-dostali-nic,n,1000288038.html
=> dziennikwschodni.pl

easylistpolish/easylistpolish_specific_block.txt
https://www.nowytydzien.pl/handlowcy-cierpia-na-przebudowie/
=> nowytydzien.pl

easylistpolish/easylistpolish_specific_block.txt
=> mlodagdynia.pl

easylistpolish/easylistpolish_specific_hide.txt
=> pkf.org.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.firmypolski.pl/katalog/kategoria/82/architektura-wnetrz
=> firmypolski.pl

easylistpolish/easylistpolish_specific_hide.txt
http://www.osowa24.pl/news.php
=> osowa24.pl

easylistpolish/easylistpolish_specific_hide.txt
http://www.rynekinstalacyjny.pl/artykul/id5303,mapa-drogowa-bim
=> rynekinstalacyjny.pl

easylistpolish/easylistpolish_specific_hide.txt
https://info-net.com.pl/katalog/katalog-sklepow-internetowych
=> info-net.com.pl

easylistpolish/easylistpolish_specific_hide.txt
https://wbaziefirm.pl/budownictwo-ogolne/architektura/prota_i967
=> wbaziefirm.pl

easylistpolish/easylistpolish_specific_block.txt
=> infokatowice.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
=> elubaczow.com

easylistpolish/easylistpolish_specific_hide.txt
=> pokerlistings.pl

easylistpolish/easylistpolish_specific_hide.txt
=> kanal10.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.spottedstarachowice.pl/fakty/item/7835-pozar-w-domu-jednorodzinnym-w-wachocku-po-wybuchu-butli-z-gazem-zdjecia.html
=> spottedstarachowice.pl

easylistpolish/easylistpolish_specific_hide.txt
-[edunews.pl](https://edunews.pl)
=> edunews.pl

easylistpolish/easylistpolish_specific_hide.txt
-[chnnews.pl](https://chnnews.pl)
=> chnnews.pl

easylistpolish/easylistpolish_specific_hide.txt
-[szpileczki.pl](http://szpileczki.pl)
=> szpileczki.pl

easylistpolish/easylistpolish_specific_block.txt
-[sportowy24.pl](https://sportowy24.pl)
=> sportowy24.pl

easylistpolish/easylistpolish_specific_block.txt
-[mojegotowanie.pl](https://www.mojegotowanie.pl)
=> mojegotowanie.pl

easylistpolish/easylistpolish_specific_block.txt
-[radionadzieja.pl](https://radionadzieja.pl)
=> radionadzieja.pl

easylistpolish/easylistpolish_specific_block.txt
-[glosojcapio.pl](https://glosojcapio.pl)
=> glosojcapio.pl

easylistpolish/easylistpolish_specific_block.txt
-[angielski.slowka.pl](http://www.angielski.slowka.pl)
=> angielski.slowka.pl

easylistpolish/easylistpolish_specific_hide.txt
=> beskidnews.pl

easylistpolish/easylistpolish_specific_hide.txt
=> naszabydgoszcz.pl

easylistpolish/easylistpolish_specific_block.txt
=> radioradom.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.turek.net.pl/
popup
=> turek.net.pl

easylistpolish/easylistpolish_specific_hide.txt
=> wyszukana.com.pl

easylistpolish/easylistpolish_specific_hide.txt
-[fm.tuba.pl](https://fm.tuba.pl)
=> fm.tuba.pl

easylistpolish/easylistpolish_specific_hide.txt
-[menshealth.pl](https://www.menshealth.pl/welcome-page,Natural_Nation_Welcomepage_maj_2021,15222)
=> menshealth.pl

easylistpolish/easylistpolish_specific_hide.txt
-[forum.optymalizacja.com](https://www.forum.optymalizacja.com)
=> forum.optymalizacja.com

easylistpolish/easylistpolish_specific_hide.txt
-[sadistic.pl](https://www.sadistic.pl/portal/3)
=> sadistic.pl

easylistpolish/easylistpolish_specific_block.txt
-[przyslijprzepis.pl](https://www.przyslijprzepis.pl/przepis/domowy-rosol-8)-[gala.pl](https://www.gala.pl/artykul/the-voice-of-poland-nowe-zasady-programu-moga-naprawde-namieszac-200813013034)-[focus.pl](https://www.focus.pl/artykul/nadlatuja-eta-akwarydy-fragmenty-ogona-komety-halleya-rozswietla-nocne-niebo-w-maju)
=> przyslijprzepis.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
https://www.bobrzanie.pl/2021/04/30/francuska-kawiarnia-zaprasza/
=> bobrzanie.pl

easylistpolish/easylistpolish_specific_block.txt
http://www.przedsiebiorcarolny.pl/index.php?itemid=5422
=> przedsiebiorcarolny.pl

easylistpolish/easylistpolish_specific_hide.txt
=> eko-mazurymariny.pl

easylistpolish/easylistpolish_specific_hide.txt
https://globenergia.pl/fotowoltaika-polska-inwestycje-praca-kadry-2021-oze/
=> globenergia.pl

easylistpolish/easylistpolish_specific_block.txt
https://biegologia.pl/biegam-i-nie-moge-schudnac/
=> biegologia.pl

easylistpolish/easylistpolish_specific_block.txt
https://sbiegacza.pl/2021/05/28/odrobina-szalenstwa-sposob-na-ruch/
=> sbiegacza.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.gorzow24.pl/
leftovers after popup
=> gorzow24.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.echogorzowa.pl/news/1/Mija-dzien/2021-05-31/poszukujemy-wspolpracownikow-lubiacych-pisac-o-gorzowie-30556.html
=> echogorzowa.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.naklo24.pl/Dziura_od_2020_roku._%E2%80%9EW_Nakle,_tu_wszystko_jest_mozliwe%E2%80%9D,83841.html
=> naklo24.pl

easylistpolish/easylistpolish_specific_hide.txt
http://www.portal-transportowy.pl/
=> portal-transportowy.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
https://www.truckitransport.pl/
=> truckitransport.pl

easylistpolish/easylistpolish_specific_hide.txt
=> 4trucks.pl

easylistpolish/easylistpolish_specific_hide.txt
=> truck-van.pl

easylistpolish/easylistpolish_specific_hide.txt
=> portalmorski.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
https://bitcoin.pl/crypto-com-raport/
=> bitcoin.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.portalspozywczy.pl/
proznia po adsach
=> portalspozywczy.pl

easylistpolish/easylistpolish_specific_block.txt
https://www.spawalnictwo.com.pl/
=> spawalnictwo.com.pl

easylistpolish/easylistpolish_specific_hide.txt
https://forumbranzowe.com/
https://forumbranzowe.com/eksport-drzwi-zwiekszyl-sie-o-1-4/
=> forumbranzowe.com

easylistpolish/easylistpolish_specific_hide.txt
=> e-golub.info.pl popup

easylistpolish/easylistpolish_specific_hide.txt
=> ad emptiness radiofm-online.com

easylistpolish/easylistpolish_specific_block.txt
=> enowiny.pl

easylistpolish/easylistpolish_specific_block.txt
=> nowinykomornickie.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
=> sloworegionu.pl

easylistpolish/easylistpolish_specific_hide.txt
=> dlaprodukcji.pl

easylistpolish/easylistpolish_specific_hide.txt
=> ekoszalin.pl

easylistpolish/easylistpolish_specific_block.txt
https://miastokolobrzeg.pl/wiadomosci/25096-podsumowanie-kite-challenge-kolobrzeg-2021.html
=> miastokolobrzeg.pl

easylistpolish/easylistpolish_specific_block.txt
=> mypolacy.de

easylistpolish/easylistpolish_specific_block.txt
=> podlaskie24.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[estadios24.pl](https://estadios24.pl/live264479,cska-moskwa-zenit-petersburg)
=> estadios24.pl

easylistpolish/easylistpolish_specific_hide.txt
-[thinkapple.pl](https://thinkapple.pl/2021/05/20/apple-watch-sterowanie-gestami-watchos-8/)
=> thinkapple.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
-[elblag.net](http://www.elblag.net)
=> elblag.net

easylistpolish/easylistpolish_specific_hide.txt
-[niewiarygodne.pl](https://niewiarygodne.pl)
=> niewiarygodne.pl

easylistpolish/easylistpolish_specific_block.txt
-[kinogo.biz](https://kinogo.biz)
=> kinogo.biz

easylistpolish/easylistpolish_specific_block.txt
https://www.tenis.net.pl/wimbledon-hubert-hurkacz-nabiera-pewnosci-siebie/
=> tenis.net.pl

easylistpolish/easylistpolish_specific_hide.txt
https://rowerowa.pl/news/----rozek-i-konwa-najlepsi-w-ultra-bike-maraton-szklarska-poreba
=> rowerowa.pl

easylistpolish/easylistpolish_specific_hide.txt
=> cowwilanowie.pl

easylistpolish/easylistpolish_specific_hide.txt
=> A: nczas.com

easylistpolish/easylistpolish_specific_block.txt
=> nowepomorze.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.erp-view.pl/erp/29583-miedzynarodowa-kancelaria-prawna-wikborg-rein-wdrozyla-system-erp-w-chmurze-maconomy-erp-firmy-deltek.html
=> erp-view.pl

easylistpolish/easylistpolish_specific_hide.txt
https://demaskator24.pl/kim-jest-wiaczeslaw-mosze-kantor-wplywowy-lider-zydow-w/ar/19669491
=> demaskator24.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.ostrowmaz.com/aktualnosci/31653
=> ostrowmaz.com

easylistpolish/easylistpolish_specific_hide.txt
=> pilkarskiswiat.com

easylistpolish/easylistpolish_specific_hide.txt
=> piast.gliwice.pl

easylistpolish/easylistpolish_specific_hide.txt
=> police24.pl

easylistpolish/easylistpolish_specific_hide.txt
https://infoskierniewice.pl/pl/
=> infoskierniewice.pl

easylistpolish/easylistpolish_specific_hide.txt
=> terazstrzelno.pl

easylistpolish/easylistpolish_specific_hide.txt
=> radzyninfo.pl

easylistpolish/easylistpolish_specific_hide.txt
https://glospowiatusredzkiego.pl/pl/
=> glospowiatusredzkiego.pl

easylistpolish/easylistpolish_specific_hide.txt
=> wrzesnia.info.pl

easylistpolish/easylistpolish_specific_hide.txt
https://e-wabrzezno.info.pl/pl/
=> e-wabrzezno.info.pl

easylistpolish/easylistpolish_specific_hide.txt
=> dziennikpolicki.pl

easylistpolish/easylistpolish_specific_hide.txt
=> ipolice.pl

easylistpolish/easylistpolish_specific_hide.txt
=> tvpolice.com.pl

easylistpolish/easylistpolish_specific_hide.txt
=> eplastics.pl

easylistpolish/easylistpolish_specific_hide.txt
=> chemical.pl

easylistpolish/easylistpolish_specific_block.txt
https://www.kwalifikacjezawodowe.info/
=> kwalifikacjezawodowe.info

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
=> studentnews.pl

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
=> wydawca.com.pl

easylistpolish/easylistpolish_specific_hide.txt
=> ecopoznan.pl

easylistpolish/easylistpolish_specific_hide.txt
=> codziennypoznan.pl

easylistpolish/easylistpolish_specific_hide.txt
=> motopoznan.com

easylistpolish/easylistpolish_specific_block.txt
=> supertydzien.pl

easylistpolish/easylistpolish_specific_hide.txt
https://czasdzieci.pl/warszawa/
=> czasdzieci.pl

easylistpolish/easylistpolish_specific_hide.txt
=> eostroleka.pl

easylistpolish/easylistpolish_specific_hide.txt
=> terazostroleka.pl

easylistpolish/easylistpolish_specific_hide.txt
https://ddbrodnica.pl/blog/2021/11/06/historia-izy-opowiedziana-przez-pacjentke-i-rodzine/
=> ddbrodnica.pl

easylistpolish/easylistpolish_specific_block.txt
=> ebrodnica.pl

easylistpolish/easylistpolish_specific_hide.txt
https://disco-polo.eu/to-jest-prawdziwe-disco-toskansky-z-premiera-pt-gwiazdy-migoca/
=> disco-polo.eu

easylistpolish/easylistpolish_specific_hide.txt
https://www.newsdiscopolo.info/elwira-mejk-zachwyca-uroda-trudno-uwierzyc-ile-ma-lat
=> newsdiscopolo.info

easylistpolish/easylistpolish_specific_hide.txt
=> pulskosmosu.pl

easylistpolish/easylistpolish_specific_hide.txt
=> egarwolin.pl

easylistpolish/easylistpolish_specific_block.txt
=> miedzyzdroje.tv

easylistpolish/easylistpolish_specific_block.txt
=> e-stargard.pl

easylistpolish/easylistpolish_specific_hide.txt
http://radomsport.pl/index.php
=> radomsport.pl

easylistpolish/easylistpolish_specific_hide.txt
https://www.szkolkarstwo.com.pl/
=> szkolkarstwo.com.pl

easylistpolish/easylistpolish_specific_block.txt
=> sportslaski.pl

easylistpolish/easylistpolish_specific_hide.txt
=> stressfree.pl

easylistpolish/easylistpolish_specific_hide.txt
=> swietokrzyskie24.eu

easylistpolish/easylistpolish_specific_hide.txt
=> sychar.org

easylistpolish/easylistpolish_specific_hide.txt
https://szubin24.pl/Wjechal_do_rowu._Pomoc_nie_byla_potrzebna,_ale_przydal_sie_alkomat,88582.html
=> szubin24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> testynaojcostwo.pl

easylistpolish/easylistpolish_specific_hide.txt
=> extrawalcz.pl

easylistpolish/easylistpolish_specific_hide.txt
=> ddwloclawek.pl

easylistpolish/easylistpolish_specific_hide.txt
=> ddtorun.pl

easylistpolish/easylistpolish_specific_hide.txt
=> faktypilskie.pl

easylistpolish/easylistpolish_specific_hide.txt
=> ciechocinek.biz

easylistpolish/easylistpolish_specific_hide.txt
=> swiecie24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> koronowo.net.pl

easylistpolish/easylistpolish_specific_hide.txt
=> zyciesokolowa.pl

easylistpolish/easylistpolish_specific_hide.txt
=> e-krajna.pl

easylistpolish/easylistpolish_specific_hide.txt
https://zyciesiedleckie.pl/pl/
=> zyciesiedleckie.pl

easylistpolish/easylistpolish_specific_hide.txt
=> kolniak24.eu

easylistpolish/easylistpolish_specific_hide.txt
=> gniewkowo.eu

easylistpolish/easylistpolish_specific_hide.txt
=> itvszubin.pl

easylistpolish/easylistpolish_specific_hide.txt
=> superchodziez.pl

easylistpolish/easylistpolish_specific_hide.txt
=> czas.tygodnik.pl

easylistpolish/easylistpolish_specific_hide.txt
=> bydgoszcz24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> tygodnik.pl

easylistpolish/easylistpolish_specific_hide.txt
=> brodnica365.pl

easylistpolish/easylistpolish_specific_hide.txt
=> pakosc24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> chocianow.com.pl

easylistpolish/easylistpolish_specific_hide.txt
=> sompolno24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> naszradziejow.pl

easylistpolish/easylistpolish_specific_hide.txt
=> hej.mielec.pl

easylistpolish/easylistpolish_specific_hide.txt
https://wiescimiedzychodzkie.pl/pl/
=> wiescimiedzychodzkie.pl

easylistpolish/easylistpolish_specific_hide.txt
=> chelmza365.pl

easylistpolish/easylistpolish_specific_hide.txt
=> portalsremski.pl

easylistpolish/easylistpolish_specific_hide.txt
=> infomogilno24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> leszno24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> wkikole.pl

easylistpolish/easylistpolish_specific_hide.txt
=> ipoddebice.pl

easylistpolish/easylistpolish_specific_hide.txt
=> faktyct.pl

easylistpolish/easylistpolish_specific_hide.txt
=> pulsciechanowa.pl

easylistpolish/easylistpolish_specific_hide.txt
=> miastko24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> iszczecinek.pl

easylistpolish/easylistpolish_specific_hide.txt
=> ejarocin.pl

easylistpolish/easylistpolish_specific_hide.txt
https://rzeczkrotoszynska.pl/pl/
=> rzeczkrotoszynska.pl

easylistpolish/easylistpolish_specific_hide.txt
=> roztocze.net

easylistpolish/easylistpolish_specific_hide.txt
=> gwarek.com.pl

easylistpolish/easylistpolish_specific_hide.txt
=> lowiczanin.info

easylistpolish/easylistpolish_specific_hide.txt
=> hej.rzeszow.pl

easylistpolish/easylistpolish_specific_hide.txt
=> pulsgminy.pl

easylistpolish/easylistpolish_specific_hide.txt
=> e-golub.info.pl

easylistpolish/easylistpolish_specific_hide.txt
https://drawskopomorskie.com/pl/
=> drawskopomorskie.com

easylistpolish/easylistpolish_specific_hide.txt
=> zawiercie365.pl

easylistpolish/easylistpolish_specific_hide.txt
=> myszkow365.pl

easylistpolish/easylistpolish_specific_hide.txt
https://ino.online/ogloszenia/nieruchomosci-mieszkania/55265/solanki-2-pokoje-49m2-ii-pietro.html
=> ino.online

easylistpolish/easylistpolish_specific_block.txt
=> rynekinformacji.pl

easylistpolish/easylistpolish_specific_hide.txt
=> nportal.no

easylistpolish/easylistpolish_specific_hide.txt
=> bielskiedrogi.pl

easylistpolish/easylistpolish_specific_hide.txt
https://glospowiatusredzkiego.pl/pl/
=> glospowiatusredzkiego.p

easylistpolish/easylistpolish_specific_hide.txt
=> mojakruszwica.pl

easylistpolish/easylistpolish_specific_hide.txt
=> abcjanikowo24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> e-chelmno.pl

easylistpolish/easylistpolish_specific_hide.txt
=> tusochaczew.pl

easylistpolish/easylistpolish_specific_hide.txt
=> tarnowska.pl

easylistpolish/easylistpolish_specific_hide.txt
=> jastrowie24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> grudziadz365.pl

easylistpolish/easylistpolish_specific_hide.txt
=> ekstrasierpc.pl

easylistpolish/easylistpolish_specific_hide.txt
=> gostyn24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> nizanskie.info

easylistpolish/easylistpolish_whitelist.txt
=> budmatauto.pl (Issue #102602)

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
=> twojradom.pl

easylistpolish/easylistpolish_specific_block_popup.txt
Block redirect popups at https://vizjer.pl/
Another alternative would be to block the following: 
```
/w0n2g1cu$popup
/kukx332zcy$popup
```
Screenshots:
=> A: https://vizjer.pl/

easylistpolish/easylistpolish_specific_hide.txt
=> A: https://businessinsider.com.pl/

easylistpolish/easylistpolish_specific_hide.txt
=> iwola.pl adv emptiness

easylistpolish/easylistpolish_specific_hide.txt
=> ibialoleka.pl adv emptiness

easylistpolish/easylistpolish_specific_hide.txt
=> wio.waw.pl adv emptiness

easylistpolish/easylistpolish_specific_hide.txt
=> ibielany.pl adv emptiness

easylistpolish/easylistpolish_specific_block.txt
=> ibemowo.pl adv emptiness

easylistpolish/easylistpolish_specific_hide.txt
=> iursus.pl adv emptiness

easylistpolish/easylistpolish_specific_hide.txt
=> iochota.pl adv emptiness

easylistpolish/easylistpolish_specific_hide.txt
=> iursynow.pl adv emptiness

easylistpolish/easylistpolish_specific_block.txt
=> iursynow.pl

easylistpolish/easylistpolish_specific_hide.txt
=> iwawer.pl adv emptiness

easylistpolish/easylistpolish_specific_hide.txt
=> iwilanow.pl adv emptiness

easylistpolish/easylistpolish_specific_hide.txt
=> iwesola.pl adv emptiness

easylistpolish/easylistpolish_specific_hide.txt
=> irembertow.pl adv emptiness

easylistpolish/easylistpolish_adservers.txt
Hey, have some adserver for you !
Screenshot:
=> A: http://strumyk.tv/

easylistpolish_adult/adult_specific_hide.txt
https://www.filmyporno.net/11429/
=> nsfw filmyporno.net

easylistpolish_adult/adult_specific_block.txt
=> nsfw sexi.pl

easylistpolish_adult/adult_specific_hide.txt
https://www.filmikiporno.tv/filmy/uczennica-zdejmuje-ubranie/
=> nsfw filmikiporno.tv

easylistpolish/easylistpolish_specific_block.txt
=> wio.waw.pl

easylistpolish/easylistpolish_specific_block.txt
=> aferyprawa.eu del

easylistpolish/easylistpolish_specific_block.txt
http://firmy.meblarstwo.eu/tech-fa-miler-firma-urzadzen-technicznych/
=> firmy.meblarstwo.eu

easylistpolish/easylistpolish_specific_hide.txt
https://kurierbytowski.com.pl/wiadomosci
=> kurierbytowski.com.pl

easylistpolish/easylistpolish_specific_block.txt
=> kurierpodlaski.pl

easylistpolish/easylistpolish_specific_block.txt
=> kuriersuwalski.pl

easylistpolish/easylistpolish_specific_block.txt
=> gazetaklobucka.pl

easylistpolish/easylistpolish_specific_hide.txt
=> wronieckibazar.pl

easylistpolish/easylistpolish_specific_hide.txt
=> issue #2623 pudelek.pl

easylistpolish/easylistpolish_specific_hide.txt
=> szczecinek.com

easylistpolish/easylistpolish_specific_hide.txt
https://www.swidniczka.com/swidnica-z-ukraina-39427
=> swidniczka.com

easylistpolish/easylistpolish_specific_block.txt
http://przyjacielprzypracy.pl/
=> del przyjacielprzypracy.pl

easylistpolish/easylistpolish_specific_block.txt
https://www.lowking.pl/znacie-mnie-jednoznaczna-deklaracja-dany-whitea-ws-wystepu-rosyjskich-zawodnikow-w-ufc/
=> del lowking.pl

easylistpolish/easylistpolish_specific_block.txt
=> del podrogach.pl

easylistpolish/easylistpolish_specific_block.txt
http://www.podhale-sport.pl/s,docid,65549.html
=> del podhale-sport.pl

easylistpolish/easylistpolish_specific_block.txt
=> del plonskwsieci.pl

easylistpolish/easylistpolish_specific_hide.txt
http://www.podhale-sport.pl/s,docid,65549.html
=> podhale-sport.pl

easylistpolish/easylistpolish_specific_block.txt
https://www.all-inclusive.com.pl/
=> all-inclusive.com.pl

easylistpolish/easylistpolish_specific_hide.txt
=> porady.mobi

easylistpolish/easylistpolish_specific_block.txt
https://przyjaznawarszawa.pl/info/item/1298-na-czym-polega-osuszanie-mieszkan?
=> przyjaznawarszawa.pl

easylistpolish/easylistpolish_specific_hide.txt
https://tvmalbork.pl/aktualnosci/35587,malbork-wedkarze-zapraszaja-do-wspolnej-akcji-sprz
=> tvmalbork.pl

easylistpolish/easylistpolish_specific_hide.txt
https://tvregionalna24.pl/aktualnosci/35588,elblag-podpalal-wiaty-smietnikowe-grozi-mu-do-5-la
=> tvregionalna24.pl

easylistpolish/easylistpolish_specific_hide.txt
=> tvdzierzgon.pl

easylistpolish/easylistpolish_specific_hide.txt
=> twojglos-garwolin.pl

easylistpolish/easylistpolish_specific_hide.txt
Sponsored content on allegro.pl
=> A: allegro.pl

easylistpolish/easylistpolish_specific_hide.txt
Fixes for [#2958](https://github.com/easylistpolish/easylistpolish/issues/2958)
Reference: https://github.com/easylistpolish/easylistpolish/commit/15f884d
=> M: Update #2958

easylistpolish/easylistpolish_specific_hide.txt
Hide banners at https://jbzd.com.pl/
Screenshot (mobile):
=> A: https://jbzd.com.pl/

easylistpolish/easylistpolish_specific_hide.txt
Hide placeholders at https://waw4free.pl/
=> A: https://waw4free.pl/

easylistpolish/easylistpolish_specific_hide.txt
Header banner + Starbucks video banner at https://allegro.pl/
=> A: https://allegro.pl/

easylistpolish/easylistpolish_adservers.txt
Banner on top,left and right side at https://poczta.o2.pl/
screenshot:
=> A: https://poczta.o2.pl/

easylistpolish/easylistpolish_specific_hide.txt
Ads between articles - https://www.money.pl/gospodarka/znaczacy-podatek-kaczynskiego-danina-uderzy-w-rozgrzany-rynek-najmu-6831480102189728a.html 
https://www.wp.pl/?src01=20804
(tested as mobile)
=> A: https://www.money.pl/

easylistpolish/easylistpolish_specific_hide.txt
video with ads popping up on top of the page on the main one and also then pressing the button to translate it.
=> A: https://www.wykop.pl/

easylistpolish/easylistpolish_specific_block.txt
In-video ads at https://desu-online.pl/
=> A: https://desu-online.pl/

easylistpolish/easylistpolish_specific_hide.txt
https://mambiznes.pl/
mambiznes.pl##.header-billboard-area
https://ithardware.pl/
ithardware.pl###art-topBaner
https://www.gramwzielone.pl/
gramwzielone.pl#?#.a:-abp-has(.a__title)
=> A: Placeholders & Banners

easylistpolish/easylistpolish_specific_hide.txt
Banner and sponsored products at https://www.ceneo.pl/Smartfony;szukaj-iphone
=> A: https://www.ceneo.pl/

easylistpolish/easylistpolish_specific_hide.txt
Ads at https://zlotowskie.pl/artykul/nie-bedziesz-burmistrzu/1435659
=> A: https://zlotowskie.pl/

easylistpolish/easylistpolish_specific_block.txt, easylistpolish/easylistpolish_specific_hide.txt
Banners and sponsored content at https://www.terazkrosno.pl/wiadomosci/19425-zubr-w-oku-fotopulapki-zobacz-nagranie
=> A: https://www.terazkrosno.pl/

easylistpolish/easylistpolish_specific_hide.txt
Hi there are a couple of ads on the domain on mobile view:
=> A:`benchmark.pl`

easylistpolish/easylistpolish_specific_hide.txt
Car rental ads widget
Get your guide ads widget
Thank you
=> A:`bartekwpodrozy.pl`

easylistpolish/easylistpolish_specific_hide.txt
Banners at: https://www.tuolawa.pl/artykul/31980,bez-pasow-bez-prawa-jazdy-i-z-przekreconym-licznikiem
=> A: https://www.tuolawa.pl/

easylistpolish/easylistpolish_specific_hide.txt
=> A: hokej.net
