easylistpolish/easylistpolish

- easylistpolish/easylistpolish_specific_block.txt
-[24gliwice.pl](https://www.24gliwice.pl/wiadomosci/nareszcie-po-kilku-miesiacach-przerwy-drogowcy-wracaja-do-remontu-ulicy-michalowskiego/)
> 24gliwice.pl

- easylistpolish/easylistpolish_specific_block.txt
- easylistpolish/easylistpolish_specific_hide.txt
-[pomorskifutbol.pl](http://pomorskifutbol.pl/news_11426_PKO-Ekstraklasa_-Rakow-Czestochowa-3-2-Arka-Gdynia.html)
> pomorskifutbol.pl

- easylistpolish/easylistpolish_specific_block.txt
-[pogonsportnet.pl](http://pogonsportnet.pl/news/kozulj-prezes-mroczek-powinien-skupic-sie-na-swoim-klubie)
> pogonsportnet.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[warzywapolowe.pl](https://www.warzywapolowe.pl)
> warzywapolowe.pl

- easylistpolish/easylistpolish_specific_block.txt
-[radioq.fm-popup](http://radioq.fm/wiadomosci/2300-ponad-1200-litrow-nielegalnego-alkoholu-zabezpieczyli-policjanci-z-kutna)
> radioq.fm-popup

- easylistpolish/easylistpolish_specific_hide.txt
-[swarzedz24.pl](https://swarzedz24.pl/znowu-wiecej-zakazen-covid-19-juz-13-przypadkow-w-gminie-swarzedz/)
> swarzedz24.pl

- easylistpolish/easylistpolish_specific_block.txt
-[sportowepodhale.pl](https://sportowepodhale.pl/)
> sportowepodhale.pl

- easylistpolish/easylistpolish_specific_hide.txt
https://poscigi.pl/mocno-wieje-zielonogorscy-strazacy-jezdza-do-powalonych-drzew/
> poscigi.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[swoszowice.org.pl](https://swoszowice.org.pl/)
> swoszowice.org.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[teraz-wilanow.pl](http://teraz-wilanow.pl)
> teraz-wilanow.pl

- easylistpolish/easylistpolish_adservers.txt
Serwery reklamowe na które trafiłem w różnych miejscach. `tvtoss` bezposrednio przekierowuje na reklamy, `pocketads` jest czasem używane na stronach wp.
> adservers: tvtoss.com + pocketads.pl

- easylistpolish/easylistpolish_specific_block.txt
-[vetopedia.pl](https://www.vetopedia.pl)
> vetopedia.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[tvnakarte.eu](https://tvnakarte.eu/index.php/aktualnosci/83-iti-neovision-zmiana-nazwy-na-canal-polska-s-a)
> tvnakarte.eu

- easylistpolish/easylistpolish_specific_block.txt
-[tojuzbylo.pl](https://tojuzbylo.pl/wiadomosc/bitwa-o-borujsk-ostatnia-szarza-polskiej-kawalerii)
> tojuzbylo.pl

- easylistpolish/easylistpolish_specific_block.txt
-[tylkonauka.pl](https://tylkonauka.pl/wiadomosc/futurolog-przewiduje-ze-do-2050-roku-ludzie-beda-mogli-porzucac-swoje-ciala-i-przenosic)
> tylkonauka.pl

- easylistpolish/easylistpolish_specific_block.txt
-[tylkomedycyna.pl](https://tylkomedycyna.pl/wiadomosc/naukowcy-znalezli-zwiazek-miedzy-otyloscia-slabym-wechem-0)
> tylkomedycyna.pl

- easylistpolish/easylistpolish_adservers.txt
https://www.ddbrodnica.pl/4678-przekroczyl-dozwolona-predkosc-w-terenie-zabudowanym-o-68-kmh
> ddbrodnica.pl

- easylistpolish/easylistpolish_specific_hide.txt
https://losice.info/wkrecone-w-nigeryjski-przekret-stracily-28-i-90-tys-zl/
> losice.info

- easylistpolish/easylistpolish_adservers.txt
https://www.grojec24.net/news-drogowcy-podsumowali-postepy-przy-budowie-nowej-trasy-grojec-warszawa,7289.html
> grojec24.net + adservers

- easylistpolish/easylistpolish_specific_hide.txt
https://infoszach.pl/2020/12/07/teclaf-i-rudzinska-mistrzami-polski-do-lat-20/
w prawym menu jest tez reklama do ciuchow ale nad nia jest info ze to sponsor itp wiec nie blokuje
> infoszach.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[podobnestrony.pl](https://podobnestrony.pl/do/zalando.pl)
> podobnestrony.pl

- easylistpolish/easylistpolish_specific_block.txt
- easylistpolish/easylistpolish_specific_hide.txt
-[motoocena.pl](https://motoocena.pl/uwaga-vw-najbardziej-zadluzona-firma-swiata/)
> motoocena.pl

- easylistpolish/easylistpolish_adservers.txt
Line 66 contains duplicated filter with another one from EasyList. FILTER: ||waytogrow.eu^-party
> [redundant] waytogrow.eu

- easylistpolish/easylistpolish_thirdparty.txt
Line 94 BLOCKING REDUNDANT to ||sbhc.portalhc.com^$third-party from EasyList, FILTER: ||sbhc.portalhc.com/172112/SearchBox^$third-party
> [redundant] remove sbhc.portalhc.com/172112/SearchBox^$third-party

- easylistpolish/easylistpolish_specific_hide.txt
Line 1573 contains specific hide filter, which is redundant to ##.ads_top_nav from EasyList, with domain(s) portalwysokichplonow.pl FILTER: portalwysokichplonow.pl##.ads_top_nav
> [redundant] portalwysokichplonow.pl##.ads_top_nav

- easylistpolish/easylistpolish_specific_hide.txt
Line 1849 contains specific hide filter, which is redundant to ##.g1-advertisement from EasyList, with domain(s) spottedlublin.pl FILTER: spottedlublin.pl##.g1-advertisement
> [redundant] spottedlublin.pl##.g1-advertisement

- easylistpolish/easylistpolish_specific_hide.txt
https://info112.pl/2021/01/12/300-gosci-w-hotelu-we-wladyslawowie-wlasciciel-twierdzil-ze-to-turniej-szachowy-zdjecia/
> info112.pl

- easylistpolish/easylistpolish_specific_hide.txt
https://krosno112.pl/aktualnosci/inne/item/10098-chore-na-telazjoze-bieszczadzkie-zubry-zostana-odstrzelone-zgode-wydala-gdos.html
> krosno112.pl

- easylistpolish/easylistpolish_specific_block.txt
https://www.rzeszow112.pl/wiadomosci/1863-koronawirus-na-podkarpaciu-sroda-13-01-2020
> rzeszow112.pl

- easylistpolish/easylistpolish_specific_hide.txt
https://www.lublin112.pl/9053-nowe-zakazenia-koronawirusem-w-kraju-493-w-woj-lubelskim-nie-zyje-481-osob-z-infekcja-covid-19/
> lublin112.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[cafesenior.pl](https://cafesenior.pl)
> cafesenior.pl

- easylistpolish/easylistpolish_specific_block.txt
- easylistpolish/easylistpolish_specific_hide.txt
-[nadwisla24.pl](https://nadwisla24.pl/2021/01/09/hit-teatralny-kolacja-dla-glupca-w-czwartek-4-marca-w-stalowej-woli/)
> nadwisla24.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[mazovia24.pl](http://www.mazovia24.pl)
> mazovia24.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[okraglemiasto.pl](https://okraglemiasto.pl/ponad-80-tysiecy-trafilo-do-puszek-kolskich-wolontariuszy/)
> okraglemiasto.pl

- easylistpolish/easylistpolish_specific_hide.txt
https://slaskiesiemianowice.pl/siemianowice-slaskie-urzednicy-im-bardziej-sie-przed-wirusem-zamykali-tym-bardziej-chorowali/
> slaskiesiemianowice.pl

- easylistpolish/easylistpolish_specific_hide.txt
https://niezalezna.pl/379423-walesa-opublikowal-liste-najwiekszych-szatanow-na-pierwszym-miejscu-prof-cenckiewicz
> niezalezna.pl

- easylistpolish/easylistpolish_specific_hide.txt
w #1828 i #1827 jest ten sam filtr (inne strony), tylko źle mi się zacommitowało
-[glostorunia.pl](http://www.glostorunia.pl)
> glostorunia.pl

- easylistpolish/easylistpolish_specific_block.txt
https://shareinfo.pl/nie-zyje-aleksander-doba-slynny-polski-podroznik-zmarl-po-zdobyciu-kilimandzaro/
> shareinfo.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[sport.radiozet.pl](https://sport.radiozet.pl/Pilka-nozna/Premier-League/Liverpool-Chelsea-Transmisja-TV-i-online.-Gdzie-obejrzec-na-zywo)
> sport.radiozet.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[antyradio.pl](https://www.antyradio.pl/Filmy-i-seriale/Filmy/Tom-Holland-nie-potrafil-wrocic-do-roli-Spider-Mana-po-Uncharted-46305)
> antyradio.pl

- easylistpolish/easylistpolish_specific_block.txt
-[gramwzielone.pl](https://gramwzielone.pl/energia-sloneczna/104915/ceny-paneli-fotowoltaicznch-z-chin-zaczely-rosnac)
> gramwzielone.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[telekamery.pl](https://telekamery.pl)
> telekamery.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[ilewazy.pl](http://www.ilewazy.pl/porcja-twarozku-domowego-z-ogorkiem-i-koperkiem)
> ilewazy.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[wiadomoscidebickie.pl](https://wiadomoscidebickie.pl/mazoretki-z-pilzna-znow-na-podium/)
> wiadomoscidebickie.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[gazetabialolecka.waw.pl](http://gazetabialolecka.waw.pl)
> gazetabialolecka.waw.pl

- easylistpolish/easylistpolish_specific_hide.txt
-[kaszuby24.pl](https://kaszuby24.pl)
> kaszuby24.pl

- easylistpolish/easylistpolish_specific_block.txt
-[kozaczek.pl](https://www.kozaczek.pl/galeria/omg-ojciec-meghan-markle-dostarczyl-list-do-domu-oprah-winfrey-zdjecia/)
> kozaczek.pl

- easylistpolish/easylistpolish_specific_block.txt
https://biegowe.pl/2021/05/od-dzisiaj-dozwolone-biegi-w-grupach-po-250-osob-jak-sprawdzic-czy-biegacz-jest-zaszczepiony.html
> biegowe.pl

- easylistpolish/easylistpolish_specific_block.txt
https://biokurier.pl/ekorynek/bio-planet-zadebiutuje-na-warszawskiej-gieldzie/
> biokurier.pl

- easylistpolish/easylistpolish_specific_hide.txt
https://gieldykryptowalut.pl/binance-przeznaczy-115-mln-na-rozwoj-kryptowalut-w-europie/
> gieldykryptowalut.pl

- easylistpolish/easylistpolish_specific_hide.txt
https://www.trojmiasto.pl/wiadomosci/Kierowco-zwolnij-przed-kaluza-n162057.html
> trojmiasto.pl adv emptiness

- easylistpolish/easylistpolish_specific_hide.txt
https://tygodnikkrag.pl/kultura/2022/02/eko-alarm-jeszcze-w-lutym-na-deskach-ndk/
> tygodnikkrag.pl
